/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultimorepasoexamen;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author david
 */
public class ciudadanosGUI extends javax.swing.JFrame implements IAyudasProvincial {

    private String nombre, provincia;
    private int hijos;
    private double sueldo;
    /**
     * Creates new form ciudadanosGUI
     */
    
    private DefaultListModel dlmCiudadanos = new DefaultListModel();
    private DefaultListModel dlmCiudadanosEvasores = new DefaultListModel();
    private DefaultListModel dlmCiudadanosOrdenar = new DefaultListModel();
    private DefaultListModel dlmCiudadanosPremiados = new DefaultListModel();
    
    Document doc = null;
    Element raiz = null;
    
    private int contador = 0;
    
    public ciudadanosGUI() {
        initComponents();
        lst_ciudadanos.setModel(dlmCiudadanos);
        lst_ciudadanosEvasores.setModel(dlmCiudadanosEvasores);
        lst_ordenar.setModel(dlmCiudadanosOrdenar);
        lst_ciudadanosPremiados.setModel(dlmCiudadanosPremiados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_ciudadanos = new javax.swing.JList<>();
        btn_leerCiudadanos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_ciudadanosEvasores = new javax.swing.JList<>();
        lbl_nombre = new javax.swing.JLabel();
        lbl_provincia = new javax.swing.JLabel();
        lbl_sueldo = new javax.swing.JLabel();
        lbl_hijos = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_provincia = new javax.swing.JTextField();
        txf_sueldo = new javax.swing.JTextField();
        txf_hijos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_ordenar = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txf_filtrarProvincia = new javax.swing.JTextField();
        btn_ordenar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_calcularAyuda = new javax.swing.JButton();
        txf_minHijos = new javax.swing.JTextField();
        txf_provinciaAyuda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_numeroCiudadanosBeneficiados = new javax.swing.JTextField();
        btn_evaluarCiudadania = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txf_ciudadanosTotales = new javax.swing.JTextField();
        txf_ciudadanosEvasores = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txf_cantidadEvadida = new javax.swing.JTextField();
        btn_premiar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_ciudadanosPremiados = new javax.swing.JList<>();
        btn_alta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lst_ciudadanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_ciudadanosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst_ciudadanos);

        btn_leerCiudadanos.setText("Leer ciudadanos");
        btn_leerCiudadanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leerCiudadanosActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lst_ciudadanosEvasores);

        lbl_nombre.setText("Nombre");

        lbl_provincia.setText("Provincia");

        lbl_sueldo.setText("Sueldo");

        lbl_hijos.setText("Hijos");

        jScrollPane3.setViewportView(lst_ordenar);

        jLabel1.setText("Provincia por lla que filtrar:");

        btn_ordenar.setText("Ordenar");
        btn_ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarActionPerformed(evt);
            }
        });

        jLabel2.setText("NumMinimoHijos");

        jLabel3.setText("Provincia");

        btn_calcularAyuda.setText("Calcular Ayudas por hijos");
        btn_calcularAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularAyudaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ciudadanos que se benefician:");

        btn_evaluarCiudadania.setText("Evaluar Ciudadania");
        btn_evaluarCiudadania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_evaluarCiudadaniaActionPerformed(evt);
            }
        });

        jLabel5.setText("Ciudadanos totales:");

        jLabel6.setText("Ciudadanos evasores:");

        txf_ciudadanosTotales.setEditable(false);

        txf_ciudadanosEvasores.setEditable(false);

        jLabel7.setText("Cantidad evadida:");

        btn_premiar.setText("Premiar");
        btn_premiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_premiarActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lst_ciudadanosPremiados);

        btn_alta.setText("ALTA");
        btn_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btn_leerCiudadanos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_hijos)
                                    .addComponent(lbl_sueldo))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_provincia)
                                .addGap(18, 18, 18)
                                .addComponent(txf_provincia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(btn_alta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txf_minHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txf_provinciaAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                        .addComponent(btn_evaluarCiudadania)
                                        .addGap(139, 139, 139))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txf_numeroCiudadanosBeneficiados, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_calcularAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(112, 112, 112)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txf_ciudadanosEvasores, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txf_ciudadanosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txf_cantidadEvadida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_premiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))
                                .addGap(52, 52, 52))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txf_filtrarProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(btn_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(344, 344, 344))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btn_leerCiudadanos)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_provincia)
                    .addComponent(txf_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sueldo)
                    .addComponent(txf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hijos)
                    .addComponent(txf_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btn_evaluarCiudadania))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txf_ciudadanosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txf_minHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txf_ciudadanosEvasores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txf_provinciaAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txf_cantidadEvadida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_calcularAyuda)
                        .addGap(4, 4, 4)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txf_numeroCiudadanosBeneficiados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txf_filtrarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_alta))
                        .addGap(18, 18, 18)
                        .addComponent(btn_ordenar)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_premiar)
                        .addGap(86, 86, 86))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_leerCiudadanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leerCiudadanosActionPerformed
        leerCiudadanos();
        leerCiudadanosEvasores();
    }//GEN-LAST:event_btn_leerCiudadanosActionPerformed

    private void lst_ciudadanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_ciudadanosMouseClicked
        Ciudadano c = (Ciudadano) dlmCiudadanos.getElementAt(lst_ciudadanos.getSelectedIndex());
        
        txf_nombre.setText(c.getNombre());
        txf_provincia.setText(c.getProvincia());
        txf_sueldo.setText(""+c.getSueldo());
        txf_hijos.setText(""+c.getHijos());
        
    }//GEN-LAST:event_lst_ciudadanosMouseClicked

    private void btn_ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarActionPerformed

        ArrayList ciudadanos = new ArrayList();
                
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {
            Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
            
            if (c.getProvincia().equals(txf_filtrarProvincia.getText().toUpperCase()) && c.getHijos() >= 1)
            {
                dlmCiudadanosOrdenar.addElement(c);
                ciudadanos.add(c);              
            }
        }
        
        ciudadanos.sort(new OrdenarPorSueldo());
        lst_ordenar.updateUI();
    }//GEN-LAST:event_btn_ordenarActionPerformed

    private void btn_calcularAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularAyudaActionPerformed

        ArrayList ciudadanos = new ArrayList();
        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {
            Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
            ciudadanos.add(c);           
        }
        
        String provincia = txf_provinciaAyuda.getText().toUpperCase();
        int hijos = Integer.parseInt(txf_minHijos.getText());
        
        calcularAyudasPorHijos(ciudadanos,hijos,provincia);
    }//GEN-LAST:event_btn_calcularAyudaActionPerformed

    private void btn_evaluarCiudadaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_evaluarCiudadaniaActionPerformed
              
        ArrayList listaCiudadanos = new ArrayList();
        ArrayList listaEvasores = new ArrayList();
        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) {
            
            Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
            listaCiudadanos.add(c);            
        }
        
        for (int i = 0; i < dlmCiudadanosEvasores.getSize(); i++) {
            
            CiudadanoEvasor c = (CiudadanoEvasor) dlmCiudadanosEvasores.get(i);
            listaEvasores.add(c);            
        }
        
        evaluarCiudadania(listaCiudadanos, listaEvasores);
    }//GEN-LAST:event_btn_evaluarCiudadaniaActionPerformed

    private void btn_premiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_premiarActionPerformed
        ArrayList nombresEvasores = new ArrayList();
        Ciudadano c = (Ciudadano) dlmCiudadanos.getElementAt(lst_ciudadanos.getSelectedIndex());
        
        for (int i = 0; i < dlmCiudadanosEvasores.getSize(); i++) 
        {
            CiudadanoEvasor cEvasor = (CiudadanoEvasor) dlmCiudadanosEvasores.get(i);
            String nombre = cEvasor.getNombre();
            
            nombresEvasores.add(nombre);
                      
        }
        if (!nombresEvasores.contains(c.getNombre()))
        {
            c.setSueldo(c.getSueldo()+1000);
            dlmCiudadanosPremiados.addElement(c);
        } 
        
        lst_ciudadanosPremiados.updateUI();
    }//GEN-LAST:event_btn_premiarActionPerformed

    private void btn_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaActionPerformed
        nombre = txf_nombre.getText();
        provincia = txf_provincia.getText();
        sueldo = Integer.parseInt(txf_sueldo.getText());
        hijos = Integer.parseInt(txf_hijos.getText());
        
        Ciudadano c = new Ciudadano(nombre, provincia, sueldo, hijos);
        dlmCiudadanos.addElement(c);
        
        txf_nombre.setText(null);
        txf_provincia.setText(null);
        txf_sueldo.setText(null);
        txf_hijos.setText(null);
        
        contador++;
    }//GEN-LAST:event_btn_altaActionPerformed

    public double evaluarCiudadania( ArrayList listaCiudadanos, ArrayList listaEvasores)
    {
        int contadorCiudadanos=0;
        int contadorCiudadanosEvasores=0;
        
        double cantidadTotalEvadida=0;
        
        double media=0;
        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {
            contadorCiudadanos++;           
        }
        
        for (int i = 0; i < dlmCiudadanosEvasores.getSize(); i++) 
        {
            CiudadanoEvasor c = (CiudadanoEvasor) dlmCiudadanosEvasores.get(i);
            cantidadTotalEvadida = cantidadTotalEvadida + c.getCantidadEvadida();
            contadorCiudadanosEvasores++;
            
            
        }
        
        txf_ciudadanosTotales.setText(""+contadorCiudadanos);
        txf_ciudadanosEvasores.setText(""+contadorCiudadanosEvasores);
        
        media = (contadorCiudadanosEvasores*100)/contadorCiudadanos;
        
        if (media > 20)
        {
            try 
            {
                throw new EPuebloEvasor(media,cantidadTotalEvadida );
            } 
            catch (EPuebloEvasor ex)
            {
                txf_cantidadEvadida.setText(media+", "+cantidadTotalEvadida);
            }
        }
        
        return media;
    }
    
    public void leerCiudadanos()
    {
        dlmCiudadanos.removeAllElements();
        
        try 
        {            
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            
            doc = db.parse("ciudadanos.xml");
            raiz = doc.getDocumentElement();
            
            NodeList nl = doc.getElementsByTagName("ciudadano");
            Element ciu = null;
            
            for (int i = 0; i < nl.getLength(); i++) {

                Ciudadano c = null;
                ciu = (Element) nl.item(i);
                c = obtenerCiudadano(ciu);
                dlmCiudadanos.addElement(c);
            }
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void leerCiudadanosEvasores()
    {
        FileReader fr=null;
        BufferedReader br=null;
        
        String linea =null;
        String trozos[];
        String trozosPuntoYcoma[];
        
        dlmCiudadanosEvasores.removeAllElements();
        
        try
        {
            fr = new FileReader("CIUDADANOS_EVASORES.txt");
            br = new BufferedReader(fr);
            
            while((linea = br.readLine())!=null)
            {
                trozos = linea.split(":");
                trozosPuntoYcoma = linea.split(";");
                
                if (trozos[0].equals("NOMBRE"))
                {
                    CiudadanoEvasor c = new CiudadanoEvasor(trozosPuntoYcoma[0].substring(7),Double.parseDouble(trozos[2]));
                    dlmCiudadanosEvasores.addElement(c);


                    lst_ciudadanosEvasores.updateUI();
                }
            }                        
        }
        catch(FileNotFoundException ex)
        {
            System.out.println(ex.getMessage());
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
        finally
        {
            try
            {
                fr.close();
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
    }
    
    public Ciudadano obtenerCiudadano(Element ciu) 
    {
        Ciudadano c = null;
        
        String nombre, provincia, sueldo, hijos;
        double dsueldo;
        int ihijos;
        
        NodeList lista = null;
        Element el;
        
        lista = ciu.getElementsByTagName("nombre");
        el = (Element) lista.item(0);
        nombre = el.getTextContent();

        
        lista = ciu.getElementsByTagName("provincia");
        el = (Element) lista.item(0);
        provincia = el.getTextContent();
        

        lista = ciu.getElementsByTagName("sueldo");
        el = (Element) lista.item(0);
        sueldo = el.getTextContent();
        dsueldo = Double.parseDouble(sueldo);
        
        lista = ciu.getElementsByTagName("hijos");
        el = (Element) lista.item(0);
        hijos = el.getTextContent();
        ihijos = Integer.parseInt(hijos);
        

        c = new Ciudadano(nombre, provincia, dsueldo,ihijos);

        return c;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ciudadanosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alta;
    private javax.swing.JButton btn_calcularAyuda;
    private javax.swing.JButton btn_evaluarCiudadania;
    private javax.swing.JButton btn_leerCiudadanos;
    private javax.swing.JButton btn_ordenar;
    private javax.swing.JButton btn_premiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_hijos;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_provincia;
    private javax.swing.JLabel lbl_sueldo;
    private javax.swing.JList<String> lst_ciudadanos;
    private javax.swing.JList<String> lst_ciudadanosEvasores;
    private javax.swing.JList<String> lst_ciudadanosPremiados;
    private javax.swing.JList<String> lst_ordenar;
    private javax.swing.JTextField txf_cantidadEvadida;
    private javax.swing.JTextField txf_ciudadanosEvasores;
    private javax.swing.JTextField txf_ciudadanosTotales;
    private javax.swing.JTextField txf_filtrarProvincia;
    private javax.swing.JTextField txf_hijos;
    private javax.swing.JTextField txf_minHijos;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JTextField txf_numeroCiudadanosBeneficiados;
    private javax.swing.JTextField txf_provincia;
    private javax.swing.JTextField txf_provinciaAyuda;
    private javax.swing.JTextField txf_sueldo;
    // End of variables declaration//GEN-END:variables

    @Override
    public int calcularAyudasPorHijos(ArrayList lista, int numeroMinimoHijos, String provincia) {
        int contador=0;
        
        for (int i = 0; i < lista.size(); i++) 
        {
            Ciudadano c = (Ciudadano) lista.get(i);
            
            if (c.getHijos() >= numeroMinimoHijos && c.getProvincia().equals(provincia))
            {
                contador++;
            }           
        }
        
        txf_numeroCiudadanosBeneficiados.setText(""+contador);
        return contador;
    }
}
