/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenisapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frameApp extends javax.swing.JFrame {

    /**
     * Creates new form frameApp
     */
    private ArrayList jugadoresAlmacen = new ArrayList();
    private int contador = 0;

    private Connection conexion = null;
    private DefaultListModel dflJugadores = new DefaultListModel();
    private DefaultListModel dflUpdate = new DefaultListModel();

   
    
    public frameApp() throws SQLException {
        initComponents();
        selectPanel.setVisible(false);
        createPanel.setVisible(false);
        deletePanel.setVisible(false);
        updatePanel.setVisible(false);
        homePanel.setVisible(true);

        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/tenis?serverTimezone=GMT",
                "root", "admin2020");
        selectAll();
        listaJugadores.setModel(dflJugadores);
        listaUpdate.setModel(dflUpdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        createButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        updateButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        selectButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        selectPanel = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txfPatrocinador = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txf_Nacionalidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_Edad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txf_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        createPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        createNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createEdad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        createNacionalidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        createMarca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUpdate = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonActualizar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txfMarcaUpdate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(760, 501));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(198, 155, 123));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createButton.setBackground(new java.awt.Color(218, 184, 139));
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(253, 246, 236));
        jLabel8.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(253, 246, 236));
        jLabel8.setText("Create");

        javax.swing.GroupLayout createButtonLayout = new javax.swing.GroupLayout(createButton);
        createButton.setLayout(createButtonLayout);
        createButtonLayout.setHorizontalGroup(
            createButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        createButtonLayout.setVerticalGroup(
            createButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createButtonLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(28, 28, 28))
        );

        jPanel2.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 90));

        deleteButton.setBackground(new java.awt.Color(218, 184, 139));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 246, 236));
        jLabel9.setText("Delete");

        javax.swing.GroupLayout deleteButtonLayout = new javax.swing.GroupLayout(deleteButton);
        deleteButton.setLayout(deleteButtonLayout);
        deleteButtonLayout.setHorizontalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        deleteButtonLayout.setVerticalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteButtonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(29, 29, 29))
        );

        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 90));

        updateButton.setBackground(new java.awt.Color(218, 184, 139));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(253, 246, 236));
        jLabel10.setText("Update");

        javax.swing.GroupLayout updateButtonLayout = new javax.swing.GroupLayout(updateButton);
        updateButton.setLayout(updateButtonLayout);
        updateButtonLayout.setHorizontalGroup(
            updateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateButtonLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel10)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        updateButtonLayout.setVerticalGroup(
            updateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateButtonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 90));

        selectButton.setBackground(new java.awt.Color(218, 184, 139));
        selectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 246, 236));
        jLabel5.setText("Select");

        javax.swing.GroupLayout selectButtonLayout = new javax.swing.GroupLayout(selectButton);
        selectButton.setLayout(selectButtonLayout);
        selectButtonLayout.setHorizontalGroup(
            selectButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectButtonLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        selectButtonLayout.setVerticalGroup(
            selectButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectButtonLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );

        jPanel2.add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -9, 190, 510));

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        selectPanel.setBackground(new java.awt.Color(253, 246, 236));
        selectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(198, 155, 123));
        Barra.setInheritsPopupMenu(true);
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/women.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/man.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(243, 233, 221));
        jLabel38.setText("Tennis App");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/red.png"))); // NOI18N

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectPanel.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/next.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        selectPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 70, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/previous.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        selectPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 70));

        jPanel14.setBackground(new java.awt.Color(243, 233, 221));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfPatrocinador.setBackground(new java.awt.Color(253, 246, 236));
        txfPatrocinador.setForeground(new java.awt.Color(169, 113, 85));
        txfPatrocinador.setDisabledTextColor(new java.awt.Color(169, 113, 85));
        txfPatrocinador.setEnabled(false);
        txfPatrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPatrocinadorActionPerformed(evt);
            }
        });
        jPanel14.add(txfPatrocinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 160, -1));

        jLabel17.setBackground(new java.awt.Color(169, 113, 85));
        jLabel17.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(169, 113, 85));
        jLabel17.setText("Patrocinador");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        txf_Nacionalidad.setBackground(new java.awt.Color(253, 246, 236));
        txf_Nacionalidad.setForeground(new java.awt.Color(169, 113, 85));
        txf_Nacionalidad.setDisabledTextColor(new java.awt.Color(169, 113, 85));
        txf_Nacionalidad.setEnabled(false);
        txf_Nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NacionalidadActionPerformed(evt);
            }
        });
        jPanel14.add(txf_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, 20));

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 113, 85));
        jLabel3.setText("Nacionalidad");
        jPanel14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txf_Edad.setBackground(new java.awt.Color(253, 246, 236));
        txf_Edad.setForeground(new java.awt.Color(169, 113, 85));
        txf_Edad.setDisabledTextColor(new java.awt.Color(169, 113, 85));
        txf_Edad.setEnabled(false);
        jPanel14.add(txf_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, -1));

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 113, 85));
        jLabel2.setText("Edad");
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txf_Nombre.setBackground(new java.awt.Color(253, 246, 236));
        txf_Nombre.setForeground(new java.awt.Color(169, 113, 85));
        txf_Nombre.setDisabledTextColor(new java.awt.Color(169, 113, 85));
        txf_Nombre.setEnabled(false);
        txf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NombreActionPerformed(evt);
            }
        });
        jPanel14.add(txf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, -1));

        jLabel1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 113, 85));
        jLabel1.setText("Nombre");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        selectPanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 350, 240));

        homePanel.setBackground(new java.awt.Color(0, 51, 204));
        homePanel.setPreferredSize(new java.awt.Dimension(690, 430));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(198, 155, 123));
        jPanel9.setPreferredSize(new java.awt.Dimension(690, 140));

        jLabel22.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(243, 233, 221));
        jLabel22.setText("Tennis App");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/man.png"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/women.png"))); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/red.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homePanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mario-gogh-MpmAzASjUaM-unsplash.jpg"))); // NOI18N
        homePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, 430));
        homePanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        deletePanel.setBackground(new java.awt.Color(253, 246, 236));
        deletePanel.setPreferredSize(new java.awt.Dimension(690, 430));
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaJugadores.setBackground(new java.awt.Color(169, 113, 85));
        listaJugadores.setForeground(new java.awt.Color(243, 233, 221));
        listaJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaJugadores);

        deletePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 520, 200));

        jPanel4.setBackground(new java.awt.Color(198, 155, 123));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(243, 233, 221));
        jLabel16.setText("Eliminar");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/ball.png"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        deletePanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 520, 60));

        jPanel8.setBackground(new java.awt.Color(198, 155, 123));
        jPanel8.setPreferredSize(new java.awt.Dimension(570, 70));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/women.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/man.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(243, 233, 221));
        jLabel35.setText("Tennis App");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/red.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        deletePanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        createPanel.setBackground(new java.awt.Color(253, 246, 236));
        createPanel.setPreferredSize(new java.awt.Dimension(690, 430));
        createPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(198, 155, 123));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(243, 233, 221));
        jLabel15.setText("Crear");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/ball.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 690, 80));

        jPanel12.setBackground(new java.awt.Color(198, 155, 123));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 143));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/man.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/women.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(243, 233, 221));
        jLabel36.setText("Tennis App");

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/red.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        createPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        jPanel13.setBackground(new java.awt.Color(243, 233, 221));

        createNombre.setBackground(new java.awt.Color(253, 246, 236));
        createNombre.setForeground(new java.awt.Color(169, 113, 85));

        jLabel11.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(169, 113, 85));
        jLabel11.setText("Nombre");

        createEdad.setBackground(new java.awt.Color(253, 246, 236));
        createEdad.setForeground(new java.awt.Color(169, 113, 85));

        jLabel13.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 113, 85));
        jLabel13.setText("Edad");

        createNacionalidad.setBackground(new java.awt.Color(253, 246, 236));
        createNacionalidad.setForeground(new java.awt.Color(169, 113, 85));
        createNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNacionalidadActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(169, 113, 85));
        jLabel14.setText("Nacionalidad");

        createMarca.setBackground(new java.awt.Color(253, 246, 236));
        createMarca.setForeground(new java.awt.Color(169, 113, 85));
        createMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMarcaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 113, 85));
        jLabel18.setText("Patrocinador");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(createNombre)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28))
        );

        createPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 390, 200));

        updatePanel.setBackground(new java.awt.Color(0, 51, 51));
        updatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaUpdate.setBackground(new java.awt.Color(169, 113, 85));
        listaUpdate.setForeground(new java.awt.Color(243, 233, 221));
        listaUpdate.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaUpdate);

        updatePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 420, 420));

        jPanel5.setBackground(new java.awt.Color(253, 246, 236));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        buttonActualizar.setBackground(new java.awt.Color(198, 155, 123));
        buttonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonActualizarMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(253, 246, 236));
        jLabel21.setText("Actualizar");

        txfMarcaUpdate.setBackground(new java.awt.Color(243, 233, 221));
        txfMarcaUpdate.setForeground(new java.awt.Color(169, 113, 85));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/ball.png"))); // NOI18N

        javax.swing.GroupLayout buttonActualizarLayout = new javax.swing.GroupLayout(buttonActualizar);
        buttonActualizar.setLayout(buttonActualizarLayout);
        buttonActualizarLayout.setHorizontalGroup(
            buttonActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txfMarcaUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(67, 67, 67))
        );
        buttonActualizarLayout.setVerticalGroup(
            buttonActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonActualizarLayout.createSequentialGroup()
                .addComponent(txfMarcaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel16.setBackground(new java.awt.Color(243, 233, 221));

        jLabel20.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(169, 113, 85));
        jLabel20.setText("Actualizar Marca");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(buttonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        updatePanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 420));

        jPanel11.setBackground(new java.awt.Color(198, 155, 123));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/man.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/women.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(243, 233, 221));
        jLabel37.setText("Tennis App");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/red.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        updatePanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(selectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 580, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonMouseClicked
        // TODO add your handling code here:

        deletePanel.setVisible(false);
        createPanel.setVisible(false);
        selectPanel.setVisible(true);
        updatePanel.setVisible(false);
        homePanel.setVisible(false);

        
         
        try{
           setInfo();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error al recuperar la información.",
             "Error!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_selectButtonMouseClicked



  


    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        nextPlayer();
    }//GEN-LAST:event_jLabel12MouseClicked
  
    private void txf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NombreActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        prevPlayer();
    }//GEN-LAST:event_jLabel4MouseClicked


    
    /*Metodo para mostrar el primer jugador en el apartado de seleccion*/
    public void setInfo() {
        jugador jgd;
        jgd = (jugador) jugadoresAlmacen.get(contador);
        txf_Nombre.setText(jgd.getNombre());
        txf_Edad.setText("" + jgd.getEdad());
        txf_Nacionalidad.setText(jgd.getNacionalidad());
        txfPatrocinador.setText(jgd.getMarca());
    }
    
    /*Evento para mostrar la ventana de creacion de un jugador*/
    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        // TODO add your handling code here:
        createPanel.setVisible(true);
        selectPanel.setVisible(false);
        deletePanel.setVisible(false);
        updatePanel.setVisible(false);
    }//GEN-LAST:event_createButtonMouseClicked

    
    /*Evento para crear un jugador*/
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
        try{
           create();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e ,
             "Error!", JOptionPane.ERROR_MESSAGE);
        }
  
    }//GEN-LAST:event_jPanel1MouseClicked
    /*Evento para mostrar la ventana de eliminacion*/
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        deletePanel.setVisible(true);
        createPanel.setVisible(false);
        selectPanel.setVisible(false);
        updatePanel.setVisible(false);

        dflJugadores.clear();

        jugador jgd;

        for (int i = 0; i < jugadoresAlmacen.size(); i++) {

            jgd = (jugador) jugadoresAlmacen.get(i);

            dflJugadores.addElement(jgd);
        }


    }//GEN-LAST:event_deleteButtonMouseClicked

    
    
    
    /*Evento para eliminar un jugador*/
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        try{
             deletePlayer();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error al borrar un jugador.",
             "Error!", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jPanel4MouseClicked
    
    /*Evento para mostrar la ventana de actulizacion*/
    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        createPanel.setVisible(false);
        selectPanel.setVisible(false);
        deletePanel.setVisible(false);
        updatePanel.setVisible(true);
        homePanel.setVisible(false);

        
        try{
               updateView();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error al actualizar un patrocinador.",
             "Error!", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_updateButtonMouseClicked

    
    
    /*Actualizar la interfaz cuando hay una actulizacion de algun campo*/
    public void updateView() {
        dflUpdate.clear();
        selectAll();
        jugador jgd;

        for (int i = 0; i < jugadoresAlmacen.size(); i++) {

            jgd = (jugador) jugadoresAlmacen.get(i);

            dflUpdate.addElement(jgd);
        }
    }
    
    
    
    /*Evento para actualizar*/
    private void buttonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonActualizarMouseClicked
        try {
            // TODO add your handling code here:
            update();

            dflUpdate.clear();

            jugador jgd;

            selectAll();

            for (int i = 0; i < jugadoresAlmacen.size(); i++) {

                jgd = (jugador) jugadoresAlmacen.get(i);

                dflUpdate.addElement(jgd);
            }
            txfMarcaUpdate.setText("");

        } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Error al actualizar un patrocinador.",
             "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonActualizarMouseClicked

    private void txf_NacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NacionalidadActionPerformed

    private void txfPatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPatrocinadorActionPerformed

    }//GEN-LAST:event_txfPatrocinadorActionPerformed

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:

  
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_BarraMouseDragged

    private void createMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMarcaActionPerformed

    private void createNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNacionalidadActionPerformed
    
    
    
    /*Metodo para mostrar un siguiente jugador  en el apartado de seleccion*/
      public void nextPlayer() {

        if (contador < jugadoresAlmacen.size()) {

            jugador jgd;
            jgd = (jugador) jugadoresAlmacen.get(contador);
            txf_Nombre.setText(jgd.getNombre());
            txf_Edad.setText("" + jgd.getEdad());
            txf_Nacionalidad.setText(jgd.getNacionalidad());
            txfPatrocinador.setText(jgd.getMarca());
            contador += 1;
        } else {
            contador = 0;
        }
    }
    
    /*Metodo para mostrar un jugador anterior en el apartado de seleccion*/
    public void prevPlayer() {
        if (contador == 0) {
            contador = jugadoresAlmacen.size() - 1;
        } else {
            jugador jgd;
            jgd = (jugador) jugadoresAlmacen.get(contador);
            txf_Nombre.setText(jgd.getNombre());
            txf_Edad.setText("" + jgd.getEdad());
            txf_Nacionalidad.setText(jgd.getNacionalidad());
            txfPatrocinador.setText(jgd.getMarca());
            contador -= 1;
        }

    }
    
    
    /*Metodo para la eliminacion de un jugador*/
    public void deletePlayer() {
        try {
            // TODO add your handling code here:

            jugador jgd;
            jgd = (jugador) dflJugadores.getElementAt(listaJugadores.getSelectedIndex());

            Statement x = conexion.createStatement();

            x.executeUpdate("delete "
                    + "from jugadores "
                    + "where idJugador = " + jgd.getId());

            x.close();

            jugadoresAlmacen.remove(listaJugadores.getSelectedIndex());
            dflJugadores.removeElementAt(listaJugadores.getSelectedIndex());

        } catch (SQLException ex) {
            Logger.getLogger(frameApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /*Actualizacion de una marca*/
    public void update() throws SQLException {

        
        Statement x = conexion.createStatement();
        try{
            
        jugador jgd;
        jgd = (jugador) dflUpdate.getElementAt(listaUpdate.getSelectedIndex());
       

        String marca;
        marca = "\"" + txfMarcaUpdate.getText() + "\"";

        

        x.executeUpdate("update jugadores "
                + "set marcaPatrocinadora = " + marca
                + " where idJugador = " + jgd.getId());

        listaUpdate.updateUI();
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Error al actualizar un patrocinador.",
             "Error!", JOptionPane.ERROR_MESSAGE);
        }finally{
                    x.close();
        }
        

        

    }

    /*Inserccion de un jugador*/
    public void create() {

        jugador jgd;
        int id, edad;
        String nombre, nacionalidad, marca;

        id = jugadoresAlmacen.size() + 1;
        nombre = "\"" + createNombre.getText() + "\"";
        edad = Integer.parseInt(createEdad.getText());
        nacionalidad = "\"" + createNacionalidad.getText() + "\"";
        marca = "\"" + createMarca.getText() + "\"";
   

        jgd = new jugador(id, edad, createNombre.getText(), createNacionalidad.getText(), createMarca.getText());

        jugadoresAlmacen.add(jgd);
        try {

            Statement x = conexion.createStatement();

            x.executeUpdate("INSERT INTO jugadores(idjugador,nombre,edad,nacionalidad,marcaPatrocinadora)"
                    + "values(" + id + ',' + nombre + ',' + edad + ',' + nacionalidad + ',' + marca + ")");

            x.close();

        } catch (SQLException ex) {
            Logger.getLogger(TenisApp.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            createEdad.setText("");
            createNombre.setText("");
            createNacionalidad.setText("");
            createMarca.setText("");
        }
    }

    
    /*Metodo para obtener todos los jugadores e incluirlos en una lista*/
    public void selectAll() {

        jugador jgd;
        int id, edad;
        String nombre, nacionalidad, patrocinador;
        jugadoresAlmacen.removeAll(jugadoresAlmacen);
        try {

            Statement x = conexion.createStatement(0, 0);

            ResultSet jugadores = x.executeQuery("select * from jugadores");

            while (jugadores.next()) {

                id = (int) jugadores.getObject("idJugador");
                edad = (int) jugadores.getObject("edad");

                nombre = (String) jugadores.getObject("nombre");
                nacionalidad = (String) jugadores.getObject("nacionalidad");
                patrocinador = (String) jugadores.getObject("marcaPatrocinadora");
                jgd = new jugador(id, edad, nombre, nacionalidad, patrocinador);

                jugadoresAlmacen.add(jgd);
            }

            jugadores.close();

            x.close();

        } catch (SQLException ex) {
            Logger.getLogger(TenisApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameApp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel buttonActualizar;
    private javax.swing.JPanel createButton;
    private javax.swing.JTextField createEdad;
    private javax.swing.JTextField createMarca;
    private javax.swing.JTextField createNacionalidad;
    private javax.swing.JTextField createNombre;
    private javax.swing.JPanel createPanel;
    private javax.swing.JPanel deleteButton;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JList<String> listaUpdate;
    private javax.swing.JPanel selectButton;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JTextField txfMarcaUpdate;
    private javax.swing.JTextField txfPatrocinador;
    private javax.swing.JTextField txf_Edad;
    private javax.swing.JTextField txf_Nacionalidad;
    private javax.swing.JTextField txf_Nombre;
    private javax.swing.JPanel updateButton;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
