/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal.v2;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;

/**
 *
 * @author carlo
 */
public class alumnoGui extends javax.swing.JFrame {

    /**
     * Creates new form alumnoGui
     */
    private int contador = 0;
    private ButtonGroup bg = new ButtonGroup();
    private DefaultListModel fichero1 = new DefaultListModel();
    private DefaultListModel fichero2 = new DefaultListModel();
    private DefaultListModel fichero3 = new DefaultListModel();
    private DefaultListModel fichero4 = new DefaultListModel();

    private ArrayList<alumno> almacenAlumnos = new ArrayList<alumno>();


     
    public alumnoGui() {
        initComponents();

        bg.add(bgFichero1);
        bg.add(bgFichero2);
        bg.add(bgFichero3);

        list_fichero1.setModel(fichero1);
        list_fichero2.setModel(fichero2);
        list_fichero3.setModel(fichero3);
        list_fichero4.setModel(fichero4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_Apellidos = new javax.swing.JTextField();
        bgFichero1 = new javax.swing.JRadioButton();
        bgFichero2 = new javax.swing.JRadioButton();
        bgFichero3 = new javax.swing.JRadioButton();
        btn_Incluir = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Cargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_fichero1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_fichero2 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_fichero3 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_fichero4 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellidos: ");

        bgFichero1.setText("Fichero 1");

        bgFichero2.setText("Fichero 2 ");

        bgFichero3.setText("Fichero 3");

        btn_Incluir.setText("Incluir");
        btn_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IncluirActionPerformed(evt);
            }
        });

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Cargar.setText("Cargar ");
        btn_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarActionPerformed(evt);
            }
        });

        list_fichero1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_fichero1);

        jLabel4.setText("Fichero 1");

        list_fichero2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_fichero2);

        jLabel5.setText("Fichero 2");

        list_fichero3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_fichero3);

        jLabel6.setText("Fichero 3");

        list_fichero4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(list_fichero4);

        jLabel7.setText("Fichero 4");

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txf_nombre))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txf_Apellidos)
                                .addComponent(bgFichero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bgFichero2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(bgFichero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnComparar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txf_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bgFichero1)
                        .addGap(18, 18, 18)
                        .addComponent(bgFichero2)
                        .addGap(18, 18, 18)
                        .addComponent(bgFichero3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Incluir)
                            .addComponent(btnComparar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Guardar)
                            .addComponent(btn_Cargar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IncluirActionPerformed
        // TODO add your handling code here:
        almacenAlumnos.add(new alumno(txf_nombre.getText(), txf_Apellidos.getText()));

        if (bgFichero1.isSelected()) {

            fichero1.addElement(almacenAlumnos.get(contador));
        } else if (bgFichero2.isSelected()) {
            fichero2.addElement(almacenAlumnos.get(contador));
        } else if (bgFichero3.isSelected()) {
            fichero3.addElement(almacenAlumnos.get(contador));
        }
        contador++;
        txf_nombre.setText(null);
        txf_nombre.setText(null);
        txf_Apellidos.setText(null);


    }//GEN-LAST:event_btn_IncluirActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        // TODO add your handling code here:

        FileWriter fw = null;
        PrintWriter pw = null;
        try {
            // TODO add your handling code here:
            fw = new FileWriter("fichero1.txt");
            pw = new PrintWriter(fw);

            for (int i = 0; i < fichero1.getSize(); i++) {

                alumno e = (alumno) fichero1.get(i);

                pw.println(e.getApellidos() + ", " + e.getNombre());

            }
        } catch (IOException ex) {

        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }
        try {
            // TODO add your handling code here:
            fw = new FileWriter("fichero2.txt");
            pw = new PrintWriter(fw);

            for (int i = 0; i < fichero2.getSize(); i++) {

                alumno e = (alumno) fichero2.get(i);

                pw.println(e.getApellidos() + ", " + e.getNombre());

            }
        } catch (IOException ex) {

        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }

        try {
            // TODO add your handling code here:
            fw = new FileWriter("fichero3.txt");
            pw = new PrintWriter(fw);

            for (int i = 0; i < fichero3.getSize(); i++) {

                alumno e = (alumno) fichero3.get(i);

                pw.println(e.getApellidos() + ", " + e.getNombre());

            }
        } catch (IOException ex) {

        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarActionPerformed
        // TODO add your handling code here:
        
        FileReader fw = null;
        BufferedReader br = null;
        String linea = null;

        String trozos[] = null;

        fichero1.clear();
        try {
            // TODO add your handling code here:
            fw = new FileReader("fichero1.txt");
            br = new BufferedReader(fw);
            while ((linea = br.readLine()) != null) {
                trozos = linea.split(",");
                alumno e = new alumno(trozos[1],trozos[0]);
                fichero1.addElement(e);
                list_fichero1.setModel(fichero1);

            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
         
        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }
        
              
        fichero2.clear();
        try {
            // TODO add your handling code here:
            fw = new FileReader("fichero2.txt");
            br = new BufferedReader(fw);
            while ((linea = br.readLine()) != null) {
                trozos = linea.split(",");
                alumno e = new alumno(trozos[1],trozos[0]);
                fichero2.addElement(e);
                list_fichero2.setModel(fichero2);

            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
         
        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }
        
               fichero3.clear();
        try {
            // TODO add your handling code here:
            fw = new FileReader("fichero3.txt");
            br = new BufferedReader(fw);
            while ((linea = br.readLine()) != null) {
                trozos = linea.split(",");
                alumno e = new alumno(trozos[1],trozos[0]);
                fichero3.addElement(e);
                list_fichero3.setModel(fichero3);

            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
         
        } finally {
            try {
                fw.close();
            } catch (Exception e) {
            }

        }
        
    }//GEN-LAST:event_btn_CargarActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        
         fichero4.clear();
        int i =0;
        
        
      alumno[] alumnosFichero1 = new alumno[fichero1.size()];
        
      fichero1.copyInto(alumnosFichero1);
      
       alumno[] alumnosFichero2 = new alumno[fichero2.size()];
        
      fichero2.copyInto(alumnosFichero2);
      
       alumno[] alumnosFichero3 = new alumno[fichero3.size()];
        
      fichero3.copyInto(alumnosFichero3);
      
      
      
      while(i<fichero1.getSize()){
          if(alumnosFichero1[i].toString().equals(alumnosFichero2[i].toString() )&& alumnosFichero1[i].toString().equals(alumnosFichero3[i].toString())){
            
              fichero4.addElement(fichero2.get(i));
           
                  
          }
           list_fichero4.setModel(fichero4);
                
          i++;
          
          
      }
    

      
     
        
    }//GEN-LAST:event_btnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alumnoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alumnoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alumnoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alumnoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alumnoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bgFichero1;
    private javax.swing.JRadioButton bgFichero2;
    private javax.swing.JRadioButton bgFichero3;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btn_Cargar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Incluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> list_fichero1;
    private javax.swing.JList<String> list_fichero2;
    private javax.swing.JList<String> list_fichero3;
    private javax.swing.JList<String> list_fichero4;
    private javax.swing.JTextField txf_Apellidos;
    private javax.swing.JTextField txf_nombre;
    // End of variables declaration//GEN-END:variables
}
