/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasoexamenfinal2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author david
 */
public class ciudadanosGUI extends javax.swing.JFrame implements IAyudasProvincial {

        private String nombre, provincia;
        private int sueldo, hijos;
        
    
    
        private DefaultListModel dlmCiudadanos = new DefaultListModel();
        private DefaultListModel dlmCiudadanosEvasores = new DefaultListModel();
        private DefaultListModel dlmCiudadanosProvincia = new DefaultListModel();
        private DefaultListModel dlmCiudadanosPremiados = new DefaultListModel();
        
        ArrayList listaCiudadanos = new ArrayList();
        ArrayList listaEvasores = new ArrayList();
        
        private int contadorCiudadanos=0;
        private int contadorEvasores=0;
        private int cantidadTotalEvadida=0;
        
        
        private int contador = 0;
        
        Document doc = null;
        Element raiz = null;

    /**
     * Creates new form ciudadanosGUI
     */
    public ciudadanosGUI() {
        initComponents();
        lst_ciudadanos.setModel(dlmCiudadanos);
        lst_ciudadanosEvasores.setModel(dlmCiudadanosEvasores);
        lst_ordenar.setModel(dlmCiudadanosProvincia);
        lst_ciudadanosPremiados.setModel(dlmCiudadanosPremiados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_ciudadanos = new javax.swing.JList<>();
        btn_leerCiudadanos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_ciudadanosEvasores = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_provincia = new javax.swing.JLabel();
        lbl_sueldo = new javax.swing.JLabel();
        lbl_hijos = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_provincia = new javax.swing.JTextField();
        txf_sueldo = new javax.swing.JTextField();
        txf_hijos = new javax.swing.JTextField();
        btn_alta = new javax.swing.JButton();
        btn_ordenarPorSueldo = new javax.swing.JButton();
        lbl_ordenar = new javax.swing.JLabel();
        txf_ordenar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_ordenar = new javax.swing.JList<>();
        lbl_ayuda = new javax.swing.JLabel();
        txf_provinciaAyuda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_ayuda = new javax.swing.JTextField();
        btn_calcularAyudas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txf_numeroHijos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txf_numCiuTotales = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txf_numCiuEvasores = new javax.swing.JTextField();
        btn_evaluarCiudadania = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txf_cantidadEvadida = new javax.swing.JTextField();
        lbl_premiar = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_ciudadanosPremiados = new javax.swing.JList<>();
        btn_premiar = new javax.swing.JButton();
        btn_guardarCiudadanos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lst_ciudadanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_ciudadanosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst_ciudadanos);

        btn_leerCiudadanos.setText("LEER CIUDADANOS");
        btn_leerCiudadanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leerCiudadanosActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lst_ciudadanosEvasores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CIUDADANOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("EVASORES");

        lbl_nombre.setText("Nombre");

        lbl_provincia.setText("Provincia");

        lbl_sueldo.setText("Sueldo");

        lbl_hijos.setText("Hijos");

        txf_provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_provinciaActionPerformed(evt);
            }
        });

        btn_alta.setText("DAR DE ALTA");
        btn_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaActionPerformed(evt);
            }
        });

        btn_ordenarPorSueldo.setText("Ordenar por sueldo");
        btn_ordenarPorSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarPorSueldoActionPerformed(evt);
            }
        });

        lbl_ordenar.setText("PROVINCIA ORDENAR");

        jScrollPane3.setViewportView(lst_ordenar);

        lbl_ayuda.setText("PROVINCIA AYUDA");

        jLabel3.setText("Ciudadanos que reciben ayuda:");

        txf_ayuda.setEditable(false);

        btn_calcularAyudas.setText("CALCULAR AYUDAS POR HIJOS");
        btn_calcularAyudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularAyudasActionPerformed(evt);
            }
        });

        jLabel4.setText("NUMERO DE HIJOS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EVALUAR CIUDADANIA");

        jLabel6.setText("CIUDADANOS TOTALES:");

        txf_numCiuTotales.setEditable(false);

        jLabel7.setText("CIUDADANOS EVASORES:");

        txf_numCiuEvasores.setEditable(false);

        btn_evaluarCiudadania.setText("EVALUAR");
        btn_evaluarCiudadania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_evaluarCiudadaniaActionPerformed(evt);
            }
        });

        jLabel8.setText("CANTIDAD EVADIDA");

        txf_cantidadEvadida.setEditable(false);

        lbl_premiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_premiar.setText("PREMIAR CIUDADANO");

        jScrollPane4.setViewportView(lst_ciudadanosPremiados);

        btn_premiar.setText("PREMIAR");
        btn_premiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_premiarActionPerformed(evt);
            }
        });

        btn_guardarCiudadanos.setText("GUARDAR");
        btn_guardarCiudadanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCiudadanosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(btn_leerCiudadanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_alta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btn_guardarCiudadanos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_ordenar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txf_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_ordenarPorSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txf_numeroHijos))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txf_ayuda))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbl_ayuda)
                                            .addGap(18, 18, 18)
                                            .addComponent(txf_provinciaAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btn_calcularAyudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_provincia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txf_provincia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_sueldo)
                                    .addComponent(lbl_hijos))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_sueldo)
                                    .addComponent(txf_hijos))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btn_evaluarCiudadania, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txf_numCiuTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txf_numCiuEvasores))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_premiar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 21, Short.MAX_VALUE))
                                            .addComponent(txf_cantidadEvadida))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_premiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(181, 181, 181)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(189, 189, 189))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_nombre)
                                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txf_numeroHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txf_numCiuTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_ayuda)
                                    .addComponent(txf_provinciaAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(txf_numCiuEvasores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txf_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_evaluarCiudadania))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_calcularAyudas)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txf_cantidadEvadida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_premiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_provincia)
                            .addComponent(txf_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ordenar)
                            .addComponent(txf_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_leerCiudadanos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ordenarPorSueldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_premiar)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sueldo)
                    .addComponent(txf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardarCiudadanos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hijos)
                    .addComponent(txf_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alta))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_leerCiudadanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leerCiudadanosActionPerformed

        leerCiudadanos();
        leerCiudadanosEvasores();

    }//GEN-LAST:event_btn_leerCiudadanosActionPerformed

    private void txf_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_provinciaActionPerformed

    private void btn_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaActionPerformed
        nombre = txf_nombre.getText();
        provincia = txf_provincia.getText();
        sueldo = Integer.parseInt(txf_sueldo.getText());
        hijos = Integer.parseInt(txf_hijos.getText());
        
        Ciudadano c = new Ciudadano(nombre, provincia, sueldo, hijos);
        dlmCiudadanos.addElement(c);
        
        txf_nombre.setText(null);
        txf_provincia.setText(null);
        txf_sueldo.setText(null);
        txf_hijos.setText(null);
        
        contador++;
    }//GEN-LAST:event_btn_altaActionPerformed

    private void lst_ciudadanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_ciudadanosMouseClicked
        
        Ciudadano c = (Ciudadano) dlmCiudadanos.getElementAt(lst_ciudadanos.getSelectedIndex());
        
        txf_nombre.setText(c.getNombre());
        txf_provincia.setText(c.getProvincia());
        txf_sueldo.setText(""+c.getSueldo());
        txf_hijos.setText(""+c.getHijos());
        
    }//GEN-LAST:event_lst_ciudadanosMouseClicked

    private void btn_ordenarPorSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarPorSueldoActionPerformed
        
        dlmCiudadanosProvincia.clear();
        
        provincia = txf_ordenar.getText().toUpperCase();
        
        Ciudadano[] ciudadanos = new Ciudadano[dlmCiudadanos.size()];
        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {            
            Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
            
            if (c.getProvincia().equals(provincia))
            {
                dlmCiudadanosProvincia.addElement(c);               
            }  
            
            dlmCiudadanosProvincia.copyInto(ciudadanos);
        }
        
        
        Arrays.sort(ciudadanos, new OrdenarPorSueldo());
        
//        for(int i=0; i<ciudadanos.length;i++)
//        {
//            dlmCiudadanosProvincia.addElement(ciudadanos[i]);
//        }
        
        lst_ordenar.updateUI();
    }//GEN-LAST:event_btn_ordenarPorSueldoActionPerformed

    private void btn_calcularAyudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularAyudasActionPerformed
        
        ArrayList ciudadanos = new ArrayList();       
        String provinciaAyuda = txf_provinciaAyuda.getText().toUpperCase();
        int numeroMinHijos = Integer.parseInt(txf_numeroHijos.getText());
        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {
            Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
            ciudadanos.add(c);
            
        }
        int resultado=0;
        resultado = calcularAyudasPorHijos(ciudadanos,numeroMinHijos,provinciaAyuda);
        
        txf_ayuda.setText(""+resultado);
    }//GEN-LAST:event_btn_calcularAyudasActionPerformed

    private void btn_evaluarCiudadaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_evaluarCiudadaniaActionPerformed

        
        for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
        {
            Ciudadano c =  (Ciudadano) dlmCiudadanos.get(i);
            
            listaCiudadanos.add(c);
            contadorCiudadanos++;
        }
        
        for (int i = 0; i < dlmCiudadanosEvasores.getSize(); i++) 
        {
            CiudadanoEvasor c = (CiudadanoEvasor) dlmCiudadanosEvasores.get(i);
            
            cantidadTotalEvadida = cantidadTotalEvadida + c.getCantidadEvadida();
            
            listaEvasores.add(c);
            contadorEvasores++;
        }
        
        evaluarCiudadania(listaCiudadanos,listaEvasores);
    }//GEN-LAST:event_btn_evaluarCiudadaniaActionPerformed

    private void btn_premiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_premiarActionPerformed
       ArrayList nombresEvasores = new ArrayList();
       Ciudadano c = (Ciudadano) dlmCiudadanos.getElementAt(lst_ciudadanos.getSelectedIndex());
        
        for (int i = 0; i < dlmCiudadanosEvasores.getSize(); i++) 
        {
            CiudadanoEvasor cEvasor = (CiudadanoEvasor) dlmCiudadanosEvasores.get(i);
            String nombre = cEvasor.getNombre();
            
            nombresEvasores.add(nombre);
                      
        }
        if (!nombresEvasores.contains(c.getNombre()))
        {
            c.setSueldo(c.getSueldo()+1000);
            dlmCiudadanosPremiados.addElement(c);
        } 
        
        lst_ciudadanosPremiados.updateUI();
                     
    }//GEN-LAST:event_btn_premiarActionPerformed

    private void btn_guardarCiudadanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCiudadanosActionPerformed
        try
        {
            DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
            
            doc = docBuilder.newDocument();
            Element rootElement = doc.createElement("Ciudadanos");
            doc.appendChild(rootElement);
            
            
            for (int i = 0; i < dlmCiudadanos.getSize(); i++) 
            {
                
                Element ciu = doc.createElement("Ciudadano");
                Ciudadano c = (Ciudadano) dlmCiudadanos.get(i);
                
                Element c1 = doc.createElement("nombre");
                c1.setTextContent(c.getNombre());
                ciu.appendChild(c1);

                Element c2 = doc.createElement("provincia");
                c2.setTextContent(""+c.getSueldo());
                ciu.appendChild(c2);
                
                Element c3 = doc.createElement("sueldo");
                c3.setTextContent(""+c.getSueldo());
                ciu.appendChild(c3);
                
                Element c4 = doc.createElement("hijos");
                c4.setTextContent(""+c.getHijos());
                ciu.appendChild(c4);
                
                rootElement.appendChild(ciu);
            }
                
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);   

            StreamResult result = new StreamResult(new File("ciudadanosGUARDAR.xml"));
            transformer.transform(source, result);      
        }
        catch (ParserConfigurationException pce)
        {
            pce.printStackTrace();
        }
        catch (TransformerException tfe)
        {
            tfe.printStackTrace();
        }
    }//GEN-LAST:event_btn_guardarCiudadanosActionPerformed

    public double evaluarCiudadania(ArrayList listaCiudadanos, ArrayList listaEvasores)
    {
        double resultado=0;
        
        txf_numCiuTotales.setText(""+contadorCiudadanos);
        txf_numCiuEvasores.setText(""+contadorEvasores);
        
        resultado = (contadorEvasores*100)/contadorCiudadanos;
       
        try
        {
            if (resultado > 20)
            {
                throw new EPuebloEvasor(resultado, cantidadTotalEvadida);
            } 
        }

        catch (EPuebloEvasor ex)
        {
            txf_cantidadEvadida.setText(resultado+", "+cantidadTotalEvadida);
        }
        
        return resultado;
        
    }


    public void leerCiudadanos()
    {
        dlmCiudadanos.removeAllElements();
        dlmCiudadanosEvasores.removeAllElements();
        
        try
        {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            
            doc = db.parse("ciudadanos.xml");
            raiz = doc.getDocumentElement();
            
            NodeList nl = doc.getElementsByTagName("ciudadano");
            Element ciu = null;
            
            for (int i = 0; i < nl.getLength(); i++) {

                Ciudadano c = null;
                ciu = (Element) nl.item(i);
                c = obtenerCiudadano(ciu);
                dlmCiudadanos.addElement(c);
            }          
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public Ciudadano obtenerCiudadano(Element ciu)
    {
        Ciudadano c = null;
        String nombre, provincia, sueldo, hijos;
        int isueldo, ihijos;
        
        
        NodeList lista = null;
        Element el;
        
        
        //NOMBRE 
        lista = ciu.getElementsByTagName("nombre");
        el = (Element) lista.item(0);
        nombre = el.getTextContent();
        
        //PROVINCIA
        lista = ciu.getElementsByTagName("provincia");
        el = (Element) lista.item(0);
        provincia = el.getTextContent();
        
        //SUELDO
        lista = ciu.getElementsByTagName("sueldo");
        el = (Element) lista.item(0);
        sueldo = el.getTextContent();
        isueldo = Integer.parseInt(sueldo);
        
        //HIJOS
        lista = ciu.getElementsByTagName("hijos");
        el = (Element) lista.item(0);
        hijos = el.getTextContent();
        ihijos = Integer.parseInt(hijos);
        

        c = new Ciudadano(nombre, provincia, isueldo, ihijos);

        return c;
    }
    
    public void leerCiudadanosEvasores()
    {
        FileReader fr=null;
        BufferedReader br=null;
        
        String linea =null;
        String trozos[];
        String trozosPuntosYComa[];
        
        dlmCiudadanosEvasores.clear();
        
        try
        {
            fr = new FileReader("ciu.txt");
            br = new BufferedReader(fr);
            
            while((linea = br.readLine())!=null)
            {               
                trozos = linea.split(":");
                trozosPuntosYComa = linea.split(";");
                
                if (trozos[0].startsWith("FICHERO"))
                {
                    
                }
                else
                {                    
                    CiudadanoEvasor c = new CiudadanoEvasor(trozosPuntosYComa[0].substring(7),Integer.parseInt(trozos[2]));
                    dlmCiudadanosEvasores.addElement(c);
                    lst_ciudadanosEvasores.updateUI();  
                }              
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        finally
        {
            try
            {
                fr.close();
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        
    }
    
    @Override
    public int calcularAyudasPorHijos(ArrayList lista, int numeroMinimoHijos, String provincia)
    {
       int contador=0;
             
        for (int i = 0; i < lista.size(); i++) 
        {
            Ciudadano c = (Ciudadano) lista.get(i);
            
            if (c.getHijos() >= numeroMinimoHijos && c.getProvincia().equals(provincia))
            {
                contador++;
            }               
        }
        
        return contador;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ciudadanosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ciudadanosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alta;
    private javax.swing.JButton btn_calcularAyudas;
    private javax.swing.JButton btn_evaluarCiudadania;
    private javax.swing.JButton btn_guardarCiudadanos;
    private javax.swing.JButton btn_leerCiudadanos;
    private javax.swing.JButton btn_ordenarPorSueldo;
    private javax.swing.JButton btn_premiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_ayuda;
    private javax.swing.JLabel lbl_hijos;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_ordenar;
    private javax.swing.JLabel lbl_premiar;
    private javax.swing.JLabel lbl_provincia;
    private javax.swing.JLabel lbl_sueldo;
    private javax.swing.JList<String> lst_ciudadanos;
    private javax.swing.JList<String> lst_ciudadanosEvasores;
    private javax.swing.JList<String> lst_ciudadanosPremiados;
    private javax.swing.JList<String> lst_ordenar;
    private javax.swing.JTextField txf_ayuda;
    private javax.swing.JTextField txf_cantidadEvadida;
    private javax.swing.JTextField txf_hijos;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JTextField txf_numCiuEvasores;
    private javax.swing.JTextField txf_numCiuTotales;
    private javax.swing.JTextField txf_numeroHijos;
    private javax.swing.JTextField txf_ordenar;
    private javax.swing.JTextField txf_provincia;
    private javax.swing.JTextField txf_provinciaAyuda;
    private javax.swing.JTextField txf_sueldo;
    // End of variables declaration//GEN-END:variables
}
