/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Albaran;
import edt5tacondeoro1.Articulo;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author usumaniana1
 */
public class DAlbaran extends javax.swing.JDialog {

    SistemaVP padre;
    
    ArrayList importePedido = new ArrayList();
    
    Albaran alb;
    
    private DecimalFormat df = new DecimalFormat("###.00");
    
    /**
     * Creates new form DAlbaran
     */
    public DAlbaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (SistemaVP) parent;
        
       txf_nombreCliente.setText(padre.p.getSocio().getNombre());
       txf_domicilio.setText(padre.p.getSocio().getDireccion());
       txf_poblacion.setText(padre.p.getSocio().getPoblacion());
       
       txf_importe.setText(""+cogerImporte());
       txf_cantidad.setText(""+df.format(cogerCantidad()));
       
       alb = new Albaran(padre.p.getSocio(), padre.p, cogerImporte());
       
      
    }
    
    public double cogerImporte()
    {
        Articulo articulo=null;
        
        double importeTotal=0;
        
        for (int i = 0; i < padre.p.getLineasPedidos().size(); i++) 
        {
            articulo = padre.p.getLineasPedidos().get(i).getArticulo();
            
            importeTotal += articulo.getPrecio()*padre.p.getLineasPedidos().get(i).getCantidad();                                   
        }
        importeTotal = importeTotal*1.21;
        
        return importeTotal;
    }
    
    public double cogerCantidad()
    {
        Articulo articulo=null;
        
        int cantidadTotal=0;
        
        for (int i = 0; i < padre.p.getLineasPedidos().size(); i++) 
        {
            articulo = padre.p.getLineasPedidos().get(i).getArticulo();
            
            cantidadTotal += padre.p.getLineasPedidos().get(i).getCantidad();
                        
        }
        
        return cantidadTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txf_nombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txf_domicilio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_poblacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_importe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txf_cantidad = new javax.swing.JTextField();
        btn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre del cliente:");

        txf_nombreCliente.setEditable(false);

        jLabel2.setText("Domicilio:");

        txf_domicilio.setEditable(false);

        jLabel3.setText("Poblacion:");

        txf_poblacion.setEditable(false);

        jLabel4.setText("Importe:");

        txf_importe.setEditable(false);

        jLabel5.setText("Cantidad:");

        txf_cantidad.setEditable(false);

        btn_imprimir.setText("IMPRIMIR");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txf_poblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txf_domicilio)
                                    .addComponent(txf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txf_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(btn_imprimir))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txf_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txf_importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_imprimir)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        guardarEnFicheroTexto();
        JOptionPane.showMessageDialog(this, "El albaran se ha imprimido correctamente","Informacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_imprimirActionPerformed

    public void guardarEnFicheroTexto()
    {
        FileWriter fw=null;
        PrintWriter pw=null;
        

        File f= new File("ALBARAN"+alb.getSocio().getNombre().toUpperCase()+".txt");
               
        try
        {
            fw = new FileWriter(f);
            pw = new PrintWriter(fw);


            pw.println("Nombre: "+alb.getSocio().getNombre());
            pw.println("Domicilio: "+alb.getSocio().getDireccion());
            pw.println("Poblacion: "+alb.getSocio().getPoblacion());
            pw.println("Cantidad: "+cogerCantidad());
            pw.println("Importe: "+df.format(cogerImporte()));
            
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
        finally
        {
            try
            {
                fw.close();
            }
            catch(Exception e2)
            {
                e2.printStackTrace();
            }
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAlbaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAlbaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAlbaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAlbaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAlbaran dialog = new DAlbaran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txf_cantidad;
    private javax.swing.JTextField txf_domicilio;
    private javax.swing.JTextField txf_importe;
    private javax.swing.JTextField txf_nombreCliente;
    private javax.swing.JTextField txf_poblacion;
    // End of variables declaration//GEN-END:variables
}
