/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Articulo;
import edt5tacondeoro1.LineaPedido;
import edt5tacondeoro1.Pedido;
import edt5tacondeoro1.Ruta;
import edt5tacondeoro1.Socio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class DCumplimentarPedido extends javax.swing.JDialog {

    SistemaVP padre;
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultListModel dlm = new DefaultListModel();
    

    /**
     * Creates new form DCumplimentarPedido
     */

    public DCumplimentarPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tbl_pedidos.setModel(dtm);
        lst_pedidos.setModel(dlm);
        padre = (SistemaVP) parent;

        String titulos[] = {"Nombre", "Precio", "Descripcion", "Cantidad"};
        dtm.setColumnIdentifiers(titulos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_pedidos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pedidos = new javax.swing.JTable();
        txt_idpedido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_genAlbaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista de Pedidos:");

        lst_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_pedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst_pedidos);

        tbl_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_pedidos);

        txt_idpedido.setEditable(false);
        txt_idpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idpedidoActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar Pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cumplimentar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_genAlbaran.setText("GENERAR ALBARAN");
        btn_genAlbaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genAlbaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_idpedido))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(btn_genAlbaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_idpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btn_genAlbaran))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pedidosMouseClicked


    }//GEN-LAST:event_tbl_pedidosMouseClicked

    private void cargarPedidos() {

        System.out.println(padre.listaPedidos.size());
        for (int i = 0; i < padre.listaPedidos.size(); i++) {
            Pedido pedido = (Pedido) padre.listaPedidos.get(i);
            pedido.setIdPedido(i + 1);
            dlm.addElement(pedido);

        }
    }


    private void lst_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_pedidosMouseClicked
        mostrarArticulos();
        Pedido pd1 = (Pedido) dlm.get(lst_pedidos.getSelectedIndex());
        txt_idpedido.setText("" + pd1.getIdPedido());
        
         padre.p = new Pedido(pd1.getSocio(), pd1.getLineasPedidos());

    }//GEN-LAST:event_lst_pedidosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        cargarPedidos();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_idpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idpedidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pedido p1 = new Pedido();
        String direccion = null;
        int numped = Integer.parseInt(txt_idpedido.getText());
        for (int i = 0; i < padre.listaPedidos.size(); i++) {
            p1 = padre.listaPedidos.get(i);
            if (p1.getIdPedido() == numped) {
                direccion = p1.getSocio().getPoblacion();
            }

        }
        String nomAlmacen = "Null";
        String nombreruta = comprobarRuta(direccion);
        if(nombreruta.equalsIgnoreCase("Norte")){
             nomAlmacen = "A";
        }else{
            nomAlmacen = "B";
        }
        
        padre.p.setSocio(p1.getSocio());
        padre.p.setIdPedido(p1.getIdPedido());
        
        

        
        JOptionPane.showMessageDialog(this, "El pedido numero: " + numped + " se va a mandar a la ruta: " + nombreruta+" almacen "+nomAlmacen, "Ruta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_genAlbaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genAlbaranActionPerformed
        DAlbaran albaran = new DAlbaran(padre, true);
        albaran.setVisible(true);
    }//GEN-LAST:event_btn_genAlbaranActionPerformed
    public String comprobarRuta(String direccion) {
        Ruta r1;
        String rutadireccion = null;
        for (int i = 0; i < padre.listaRutas.size(); i++) {
            r1 = padre.listaRutas.get(i);
            String[] area = r1.getAreaInfluencia();
            for (int j = 0; j < area.length; j++) {
                String nombrearea = area[j];
                if (nombrearea.equals(direccion)) {
                    rutadireccion = r1.getNombre();

                }
            }
        }
        return rutadireccion;
    }

    public void suficientoStock() {

    }

    public void mostrarArticulos() {

        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        tbl_pedidos.updateUI();

        int pedido = lst_pedidos.getSelectedIndex();

        Pedido ped1 = (Pedido) dlm.getElementAt(pedido);

        ArrayList<LineaPedido> listaPedidos = ped1.getLineasPedidos();

        for (int i = 0; i < listaPedidos.size(); i++) {
            LineaPedido linea1;

            linea1 = listaPedidos.get(i);

            Articulo art = new Articulo();

            art = linea1.getArticulo();

            String datos[] = new String[4];
            double total;

            datos[0] = art.getNombre();
            datos[1] = "" + art.getPrecio();
            datos[2] = art.getDescripcion();
            datos[3] = "" + linea1.getCantidad();

            dtm.addRow(datos);

            tbl_pedidos.updateUI();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DCumplimentarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DCumplimentarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DCumplimentarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DCumplimentarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DCumplimentarPedido dialog = new DCumplimentarPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void imprimirPedidos(List<Articulo> Lista) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_genAlbaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_pedidos;
    private javax.swing.JTable tbl_pedidos;
    private javax.swing.JTextField txt_idpedido;
    // End of variables declaration//GEN-END:variables
}
