/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondelibros;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author usumaniana1
 */
public class librosGUI extends javax.swing.JFrame {

    /**
     * Creates new form librosGUI
     */
    
    private ArrayList<Libro> almacenLibros = new ArrayList<Libro>();
    private DefaultListModel dlm;
    
    private String titulo, autor, isbn;
    private double precio;
    
    public librosGUI() {
        initComponents();
        dlm = new DefaultListModel();
        lst_libros.setModel(dlm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txf_titulo = new javax.swing.JTextField();
        txf_autor = new javax.swing.JTextField();
        txf_isbn = new javax.swing.JTextField();
        txf_precio = new javax.swing.JTextField();
        btn_incluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_libros = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        itm_guardar = new javax.swing.JMenuItem();
        itm_cargar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itm_ordenarPorAutor = new javax.swing.JMenuItem();
        itm_ordenarPorPrecio = new javax.swing.JMenuItem();
        itm_ordenarPorTitulo = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel1.setText("TItulo");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel2.setText("Autor");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel3.setText("ISBN");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel4.setText("Precio");

        txf_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_autorActionPerformed(evt);
            }
        });

        txf_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_isbnActionPerformed(evt);
            }
        });

        txf_precio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txf_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_precioActionPerformed(evt);
            }
        });

        btn_incluir.setBackground(new java.awt.Color(199, 215, 223));
        btn_incluir.setForeground(new java.awt.Color(1, 1, 1));
        btn_incluir.setText("Incluir");
        btn_incluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_incluirActionPerformed(evt);
            }
        });

        lst_libros.setBackground(new java.awt.Color(171, 231, 231));
        lst_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(lst_libros);

        jLabel5.setBackground(new java.awt.Color(113, 113, 113));
        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("GESTION DE LIBROS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setBackground(new java.awt.Color(175, 166, 166));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu4.setText("Archivo");

        itm_guardar.setText("Guardar");
        itm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_guardarActionPerformed(evt);
            }
        });
        jMenu4.add(itm_guardar);

        itm_cargar.setText("Cargar");
        itm_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_cargarActionPerformed(evt);
            }
        });
        jMenu4.add(itm_cargar);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Ordenar");

        itm_ordenarPorAutor.setText("Ordenar por Autor");
        itm_ordenarPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ordenarPorAutorActionPerformed(evt);
            }
        });
        jMenu1.add(itm_ordenarPorAutor);

        itm_ordenarPorPrecio.setText("Ordenar por Precio");
        itm_ordenarPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ordenarPorPrecioActionPerformed(evt);
            }
        });
        jMenu1.add(itm_ordenarPorPrecio);

        itm_ordenarPorTitulo.setText("Ordenar por Titulo");
        itm_ordenarPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ordenarPorTituloActionPerformed(evt);
            }
        });
        jMenu1.add(itm_ordenarPorTitulo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_autor)
                                    .addComponent(txf_isbn)
                                    .addComponent(txf_titulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btn_incluir)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_isbnActionPerformed

    private void txf_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_precioActionPerformed

    private void btn_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_incluirActionPerformed
        
        titulo = txf_titulo.getText();
        autor = txf_autor.getText();
        isbn = txf_isbn.getText();
        precio = Double.parseDouble(txf_precio.getText());
        
        Libro l = new Libro(titulo, autor, isbn, precio);
        almacenLibros.add(l);
        
        dlm.addElement(l);;

    }//GEN-LAST:event_btn_incluirActionPerformed

    private void itm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_guardarActionPerformed
        
        FileWriter fw=null;
        PrintWriter pw=null;
        
            try
            {
                fw = new FileWriter("libros.txt");
                pw = new PrintWriter(fw);

                for (int i=0;i< dlm.getSize();i++)
                {
                    Libro l = (Libro) dlm.get(i);
                    pw.println(l.toString());
                }
            }
            catch(IOException ex)
            {
                Logger.getLogger(librosGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally
            {
                try
                {
                    fw.close();
                }
                catch(Exception e2)
                {
                    e2.printStackTrace();
                }
            }
    }//GEN-LAST:event_itm_guardarActionPerformed

    private void itm_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_cargarActionPerformed
        
        FileReader fw = null;
        BufferedReader br = null;
        String linea = null;
        
        String trozos[] = null;
        
        dlm.clear();
        try
        {
            fw = new FileReader("libros.txt");
            br = new BufferedReader(fw);
            
            while ((linea = br.readLine()) != null)
            {
                trozos = linea.split(",");
                Libro l = new Libro(trozos[0], trozos[1], trozos[2], Double.parseDouble(trozos[3]));
                dlm.addElement(l);
            }
        }
        catch (FileNotFoundException ex)
        {
            System.out.println(ex.getMessage());
        }
        catch (IOException ex)
        {
            Logger.getLogger(librosGUI.class.getName()).log(Level.SEVERE, null, ex);            
        }
        finally
        {
            try
            {
                fw.close();
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_itm_cargarActionPerformed

    private void itm_ordenarPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ordenarPorAutorActionPerformed
        
        Libro[] l = new Libro[dlm.size()];
        dlm.copyInto(l);
        dlm.clear();
        Arrays.sort(l, new ordenarPorAutor());
        
        for(int i=0; i<l.length;i++)
        {
            dlm.addElement(l[i]);
        }
        
        lst_libros.updateUI();
    }//GEN-LAST:event_itm_ordenarPorAutorActionPerformed

    private void itm_ordenarPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ordenarPorPrecioActionPerformed

        Libro[] l = new Libro[dlm.size()];
        dlm.copyInto(l);
        dlm.clear();
        Arrays.sort(l, new ordenarPorPrecio());
        
        for(int i=0; i<l.length;i++)
        {
            dlm.addElement(l[i]);
        }
        
        lst_libros.updateUI();
    }//GEN-LAST:event_itm_ordenarPorPrecioActionPerformed

    private void itm_ordenarPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ordenarPorTituloActionPerformed
    
        Libro[] l = new Libro[dlm.size()];
        dlm.copyInto(l);
        dlm.clear();
        Arrays.sort(l, new ordenarPorTitulo());
        
        for(int i=0; i<l.length;i++)
        {
            dlm.addElement(l[i]);
        }
        
        lst_libros.updateUI();
    }//GEN-LAST:event_itm_ordenarPorTituloActionPerformed

    private void txf_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_autorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_incluir;
    private javax.swing.JMenuItem itm_cargar;
    private javax.swing.JMenuItem itm_guardar;
    private javax.swing.JMenuItem itm_ordenarPorAutor;
    private javax.swing.JMenuItem itm_ordenarPorPrecio;
    private javax.swing.JMenuItem itm_ordenarPorTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_libros;
    private javax.swing.JTextField txf_autor;
    private javax.swing.JTextField txf_isbn;
    private javax.swing.JTextField txf_precio;
    private javax.swing.JTextField txf_titulo;
    // End of variables declaration//GEN-END:variables
}
