/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author usuario
 */
public class DAnadirReserva extends javax.swing.JDialog {

    Fondo5 fondo = new Fondo5();
    restauranteGUI padre;
    
    int xMouse, yMouse;
    /**
     * Creates new form DAnadirReserva
     */
    public DAnadirReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondo);
        initComponents();
        padre = (restauranteGUI)parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_fechaReserva = new javax.swing.JLabel();
        lbl_comensales = new javax.swing.JLabel();
        lbl_idmesa = new javax.swing.JLabel();
        lbl_idcliente = new javax.swing.JLabel();
        txf_fecha = new javax.swing.JTextField();
        txf_comensales = new javax.swing.JTextField();
        txf_idcliente = new javax.swing.JTextField();
        txf_idmesa = new javax.swing.JTextField();
        pnl_anadir = new javax.swing.JPanel();
        lbl_anadir = new javax.swing.JLabel();
        pnl_barra = new javax.swing.JPanel();
        pnl_cerrar = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        lbl_titulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl_titulo.setText("NUEVA RESERVA");

        lbl_fechaReserva.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lbl_fechaReserva.setText("FECHA:");

        lbl_comensales.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lbl_comensales.setText("CANTIDAD DE COMENSALES:");

        lbl_idmesa.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lbl_idmesa.setText("IDMESA:");

        lbl_idcliente.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lbl_idcliente.setText("IDCLIENTE:");

        pnl_anadir.setBackground(new java.awt.Color(204, 204, 204));

        lbl_anadir.setBackground(new java.awt.Color(204, 204, 204));
        lbl_anadir.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lbl_anadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_anadir.setText("AÑADIR");
        lbl_anadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_anadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anadirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_anadirLayout = new javax.swing.GroupLayout(pnl_anadir);
        pnl_anadir.setLayout(pnl_anadirLayout);
        pnl_anadirLayout.setHorizontalGroup(
            pnl_anadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_anadir, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnl_anadirLayout.setVerticalGroup(
            pnl_anadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_anadir, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnl_barra.setBackground(new java.awt.Color(204, 204, 204));
        pnl_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barraMouseDragged(evt);
            }
        });
        pnl_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barraMousePressed(evt);
            }
        });

        pnl_cerrar.setBackground(new java.awt.Color(204, 204, 204));

        lbl_cerrar.setBackground(new java.awt.Color(204, 204, 204));
        lbl_cerrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("<-");
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_cerrarLayout = new javax.swing.GroupLayout(pnl_cerrar);
        pnl_cerrar.setLayout(pnl_cerrarLayout);
        pnl_cerrarLayout.setHorizontalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        pnl_cerrarLayout.setVerticalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_barraLayout = new javax.swing.GroupLayout(pnl_barra);
        pnl_barra.setLayout(pnl_barraLayout);
        pnl_barraLayout.setHorizontalGroup(
            pnl_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barraLayout.createSequentialGroup()
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_barraLayout.setVerticalGroup(
            pnl_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_fechaReserva)
                            .addComponent(lbl_comensales)
                            .addComponent(lbl_idcliente)
                            .addComponent(lbl_idmesa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txf_comensales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addComponent(txf_idcliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txf_idmesa, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(pnl_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl_titulo)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fechaReserva)
                    .addComponent(txf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_comensales)
                    .addComponent(txf_comensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idcliente)
                    .addComponent(txf_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idmesa)
                    .addComponent(txf_idmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(pnl_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_anadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anadirMouseClicked
        if (txf_fecha.getText().equals("") || txf_comensales.getText().toString().equals("") || txf_idcliente.getText().toString().equals("") || txf_idmesa.getText().toString().equals(""))
        {
           JOptionPane.showMessageDialog(null, "Debe rellenar los campos","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {       
            try
            {
                int res=0;
                PreparedStatement ps = null;
                Connection conex = padre.hazConexion();

                ps = conex.prepareStatement("INSERT INTO RESERVAS(fecha,ctdcomensales,idcliente,idmesa) VALUES (?,?,?,?)");
                ps.setString(1, txf_fecha.getText());
                ps.setString(2, txf_comensales.getText());
                ps.setString(3, txf_idcliente.getText());
                ps.setString(4, txf_idmesa.getText());

                res = ps.executeUpdate();

                if (res>0)
                {
                    JOptionPane.showMessageDialog(null, "Reserva añadida correctamente");
                    txf_fecha.setText("");
                    txf_comensales.setText("");
                    txf_idcliente.setText("");
                    txf_idmesa.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "ERROR. No se añadió la reserva");
                }
                ps.close();
                conex.close();


            }
            catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_lbl_anadirMouseClicked

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        this.dispose();

        DClientes clientes = new DClientes(padre, true);
        clientes.setVisible(true);
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void lbl_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseEntered
        pnl_cerrar.setBackground(Color.red);
        lbl_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_cerrarMouseEntered

    private void lbl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseExited
        pnl_cerrar.setBackground(Color.lightGray);
        lbl_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_cerrarMouseExited

    private void pnl_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_pnl_barraMouseDragged

    private void pnl_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnl_barraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAnadirReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAnadirReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAnadirReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAnadirReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAnadirReserva dialog = new DAnadirReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    class Fondo5 extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/reserva3.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_anadir;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_comensales;
    private javax.swing.JLabel lbl_fechaReserva;
    private javax.swing.JLabel lbl_idcliente;
    private javax.swing.JLabel lbl_idmesa;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_anadir;
    private javax.swing.JPanel pnl_barra;
    private javax.swing.JPanel pnl_cerrar;
    private javax.swing.JTextField txf_comensales;
    private javax.swing.JTextField txf_fecha;
    private javax.swing.JTextField txf_idcliente;
    private javax.swing.JTextField txf_idmesa;
    // End of variables declaration//GEN-END:variables
}
