/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import java.sql.*;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class DReservas extends javax.swing.JDialog {

    
    Fondo4 fondo = new Fondo4();
    restauranteGUI padre;
    
    int xMouse, yMouse;

    
    private DefaultTableModel dtmReservas = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int row, int col)
        {
            row = tbl_reservas.getSelectedRow();
            col = tbl_reservas.getSelectedColumn();
            
            if (col == 0 || col == 1)
            {
                return true;
            }
            
            return false;
        }
    };

    /**
     * Creates new form DReservas
     */
    public DReservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondo);
        initComponents();
        padre = (restauranteGUI)parent;
             
        tbl_reservas.setModel(dtmReservas);
        
        String titulos[] = {"IDRESERVA","FECHA","COMENSALES","IDCLIENTE", "IDMESA"};
        dtmReservas.setColumnIdentifiers(titulos);
        
        mostrarReservas(0,null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_reservas = new javax.swing.JTable();
        pnl_eliminarReserva = new javax.swing.JPanel();
        lbl_eliminarReserva = new javax.swing.JLabel();
        pnl_modificarReserva = new javax.swing.JPanel();
        lbl_modificarReserva = new javax.swing.JLabel();
        pnl_barra = new javax.swing.JPanel();
        pnl_cerrar = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();
        pnl_retroceder = new javax.swing.JPanel();
        lbl_retroceder = new javax.swing.JLabel();
        cbox_filtrarReservas = new javax.swing.JComboBox<>();
        txf_filtrarReservas = new javax.swing.JTextField();
        btn_buscarReservas = new javax.swing.JButton();
        pnl_anadirReserva = new javax.swing.JPanel();
        lbl_anadirReserva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        lbl_titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("RESERVAS");

        tbl_reservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_reservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_reservas);

        lbl_eliminarReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_eliminarReserva.setText("ELIMINAR");
        lbl_eliminarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_eliminarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eliminarReservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_eliminarReservaLayout = new javax.swing.GroupLayout(pnl_eliminarReserva);
        pnl_eliminarReserva.setLayout(pnl_eliminarReservaLayout);
        pnl_eliminarReservaLayout.setHorizontalGroup(
            pnl_eliminarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_eliminarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        pnl_eliminarReservaLayout.setVerticalGroup(
            pnl_eliminarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_eliminarReservaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_eliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_modificarReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_modificarReserva.setText("MODIFICAR");
        lbl_modificarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_modificarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_modificarReservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_modificarReservaLayout = new javax.swing.GroupLayout(pnl_modificarReserva);
        pnl_modificarReserva.setLayout(pnl_modificarReservaLayout);
        pnl_modificarReservaLayout.setHorizontalGroup(
            pnl_modificarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_modificarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnl_modificarReservaLayout.setVerticalGroup(
            pnl_modificarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_modificarReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_barra.setBackground(new java.awt.Color(204, 204, 204));
        pnl_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barraMouseDragged(evt);
            }
        });
        pnl_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barraMousePressed(evt);
            }
        });

        pnl_cerrar.setBackground(new java.awt.Color(204, 204, 204));

        lbl_cerrar.setBackground(new java.awt.Color(204, 204, 204));
        lbl_cerrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("X");
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_cerrarLayout = new javax.swing.GroupLayout(pnl_cerrar);
        pnl_cerrar.setLayout(pnl_cerrarLayout);
        pnl_cerrarLayout.setHorizontalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        pnl_cerrarLayout.setVerticalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbl_retroceder.setBackground(new java.awt.Color(204, 204, 204));
        lbl_retroceder.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_retroceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_retroceder.setText("<-");
        lbl_retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_retrocederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_retrocederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_retrocederMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_retrocederLayout = new javax.swing.GroupLayout(pnl_retroceder);
        pnl_retroceder.setLayout(pnl_retrocederLayout);
        pnl_retrocederLayout.setHorizontalGroup(
            pnl_retrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_retrocederLayout.createSequentialGroup()
                .addComponent(lbl_retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_retrocederLayout.setVerticalGroup(
            pnl_retrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_retroceder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_barraLayout = new javax.swing.GroupLayout(pnl_barra);
        pnl_barra.setLayout(pnl_barraLayout);
        pnl_barraLayout.setHorizontalGroup(
            pnl_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barraLayout.createSequentialGroup()
                .addComponent(pnl_retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_barraLayout.setVerticalGroup(
            pnl_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barraLayout.createSequentialGroup()
                .addComponent(pnl_retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cbox_filtrarReservas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todos", "Identificacion", "Fecha", "Identificacion cliente" }));

        btn_buscarReservas.setText("Buscar");
        btn_buscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarReservasActionPerformed(evt);
            }
        });

        lbl_anadirReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_anadirReserva.setText("AÑADIR");
        lbl_anadirReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_anadirReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anadirReservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_anadirReservaLayout = new javax.swing.GroupLayout(pnl_anadirReserva);
        pnl_anadirReserva.setLayout(pnl_anadirReservaLayout);
        pnl_anadirReservaLayout.setHorizontalGroup(
            pnl_anadirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_anadirReservaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_anadirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_anadirReservaLayout.setVerticalGroup(
            pnl_anadirReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_anadirReservaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_anadirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_anadirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(pnl_eliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(pnl_modificarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(cbox_filtrarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_filtrarReservas)
                .addGap(18, 18, 18)
                .addComponent(btn_buscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_titulo)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_filtrarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_filtrarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarReservas))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_modificarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_eliminarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_anadirReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_reservasMouseClicked
        
    }//GEN-LAST:event_tbl_reservasMouseClicked

        
    public boolean isCellEditable(int row, int column) {
       return false;       
    }
    private void lbl_eliminarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eliminarReservaMouseClicked
        try
        {
            eliminarReserva();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una reserva de la lista","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbl_eliminarReservaMouseClicked

    private void lbl_modificarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_modificarReservaMouseClicked
        try
        {
            actualizarReserva();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una reserva de la lista","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbl_modificarReservaMouseClicked

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void lbl_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseEntered
        pnl_cerrar.setBackground(Color.red);
        lbl_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_cerrarMouseEntered

    private void lbl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseExited
        pnl_cerrar.setBackground(Color.lightGray);
        lbl_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_cerrarMouseExited

    private void lbl_retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_retrocederMouseClicked
        this.dispose();

        DEntrar entrar = new DEntrar(padre, true);
        entrar.setVisible(true);

    }//GEN-LAST:event_lbl_retrocederMouseClicked

    private void lbl_retrocederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_retrocederMouseEntered
        pnl_retroceder.setBackground(Color.RED);
    }//GEN-LAST:event_lbl_retrocederMouseEntered

    private void lbl_retrocederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_retrocederMouseExited
        pnl_retroceder.setBackground(Color.lightGray);
    }//GEN-LAST:event_lbl_retrocederMouseExited

    private void pnl_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_pnl_barraMouseDragged

    private void pnl_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnl_barraMousePressed

    private void btn_buscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarReservasActionPerformed
        int opcion = cbox_filtrarReservas.getSelectedIndex();
        String valorBuscado = txf_filtrarReservas.getText();

        mostrarReservas(opcion, valorBuscado);

    }//GEN-LAST:event_btn_buscarReservasActionPerformed

    private void lbl_anadirReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anadirReservaMouseClicked
        this.dispose();

        DAnadirReserva reserva = new DAnadirReserva(padre,true);
        reserva.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_anadirReservaMouseClicked

    
    public void eliminarReserva()
    {
        Connection conex = hazConexion5();
        int fila = tbl_reservas.getSelectedRow();
        String valor = tbl_reservas.getValueAt(fila, 0).toString();
        
        try 
        {
            PreparedStatement eliminar = conex.prepareStatement("DELETE FROM reservas WHERE idreserva='"+valor+"'");
            eliminar.executeUpdate();
            dtmReservas.removeRow(tbl_reservas.getSelectedRow());
            
            JOptionPane.showMessageDialog(null, "Reserva eliminada correctamente","Informacion",JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar la reserva","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void actualizarReserva()
    {
        int fila = tbl_reservas.getSelectedRow();
        int id = Integer.parseInt(this.tbl_reservas.getValueAt(fila,0).toString());
        
        String fecha = tbl_reservas.getValueAt(fila, 2).toString();
        
        try
        {
            Connection conex = hazConexion5();
            
            PreparedStatement st = conex.prepareStatement("UPDATE reservas SET fecha='"+fecha+"'"
                    + "                                    WHERE idreserva='"+id+"'");
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Reserva actualizada correctamente");
            
        }
        catch(SQLException ex)
        {
             JOptionPane.showMessageDialog(null, "ERROR. No se pudo actualizar la reserva");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DReservas dialog = new DReservas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    public void mostrarReservas(int opBuscar, String valor)
    {
        dtmReservas.setRowCount(0);
        
        String codsql=null;
        
        if (opBuscar == 0 && valor == null)
        {
            codsql = "SELECT * FROM RESERVAS";
        }
        else
        {
            if (opBuscar == 1 && valor != null)
            {
                codsql = "SELECT * FROM RESERVAS WHERE idreserva = '"+valor+"'";
            }
            else
            {
                if (opBuscar == 2 && valor !=null)
                {
                    codsql = "SELECT * FROM RESERVAS WHERE fecha = '"+valor+"'";
                }
                else
                {
                    if (opBuscar == 3 && valor !=null)
                    {
                        codsql = "SELECT * FROM RESERVAS WHERE idcliente ='"+valor+"'";
                    }
                    else
                    {
                        codsql = "SELECT * FROM RESERVAS";
                    }
                }               
            }
        }
        
        try
        {
            Connection conex = hazConexion5();
        
        
            Statement s = conex.createStatement();
        
            ResultSet rs = s.executeQuery(codsql);
            
            
            while (rs.next())
            {
                Object [] fila = new Object[5];
                
                for (int i=0;i<5;i++)
                {
                    fila[i] = rs.getObject(i+1);
                    
                }
                dtmReservas.addRow(fila);
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public Connection hazConexion5()
    {
        Connection conexion = null;
        try
        {
            DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/meltdown?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","toor");
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
        
        return conexion;
    }
    
    class Fondo4 extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo2.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarReservas;
    private javax.swing.JComboBox<String> cbox_filtrarReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_anadirReserva;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_eliminarReserva;
    private javax.swing.JLabel lbl_modificarReserva;
    private javax.swing.JLabel lbl_retroceder;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_anadirReserva;
    private javax.swing.JPanel pnl_barra;
    private javax.swing.JPanel pnl_cerrar;
    private javax.swing.JPanel pnl_eliminarReserva;
    private javax.swing.JPanel pnl_modificarReserva;
    private javax.swing.JPanel pnl_retroceder;
    private javax.swing.JTable tbl_reservas;
    private javax.swing.JTextField txf_filtrarReservas;
    // End of variables declaration//GEN-END:variables
}
