/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad_5.pkg7;


import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author usumaniana1
 */
public class guiEquipos extends javax.swing.JFrame {

    /**
     * Creates new form guiEquipos
     */
    
    private DefaultListModel listaEquipos;
    private DefaultListModel listaEntrenadores;
    private DefaultListModel listaNoSancionados;
    private DefaultListModel listaSancionados;
    
    Document doc = null;
    Element raiz = null;    
    
    
    
    public guiEquipos() {
        initComponents();
        
        
        listaSancionados = new DefaultListModel();
        listaEquipos = new DefaultListModel();
        listaEntrenadores = new DefaultListModel();
        listaNoSancionados = new DefaultListModel();
        
        lst_Sancionados.setModel(listaSancionados);
        lst_Equipos.setModel(listaEquipos);
        lst_Entrenadores.setModel(listaEntrenadores);
        lst_noSancionado.setModel(listaNoSancionados);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_AltaEquipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Equipos = new javax.swing.JList<>();
        txf_equipoNombre = new javax.swing.JTextField();
        txf_equipoPuntos = new javax.swing.JTextField();
        txf_equiposEntrenador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_entrenadorNombre = new javax.swing.JTextField();
        txt_entrenadorEdad = new javax.swing.JTextField();
        btn_Entrenador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_Entrenadores = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_noSancionado = new javax.swing.JList<>();
        btn_ObtenerEquipos = new javax.swing.JButton();
        btn_OrdenarPuntos = new javax.swing.JButton();
        btn_guardarTodo = new javax.swing.JButton();
        btn_OrdenarTodo = new javax.swing.JButton();
        btn_guardarXml = new javax.swing.JButton();
        btn_guardarJson = new javax.swing.JButton();
        btn_recuperarXml = new javax.swing.JButton();
        btn_recuperarJson = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_recuperarSeriando = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_Sancionados = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntos");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entrenador");

        btn_AltaEquipo.setText("Alta");
        btn_AltaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AltaEquipoActionPerformed(evt);
            }
        });

        lst_Equipos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_EquiposValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lst_Equipos);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Equipos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_equipoPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txf_equipoNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txf_equiposEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_AltaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txf_equipoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_equipoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txf_equiposEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btn_AltaEquipo))
                    .addComponent(jScrollPane2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Entrenadores");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edad:");

        btn_Entrenador.setText("Alta");
        btn_Entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrenadorActionPerformed(evt);
            }
        });

        lst_Entrenadores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_EntrenadoresValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lst_Entrenadores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_entrenadorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txt_entrenadorEdad)))
                            .addComponent(btn_Entrenador))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_entrenadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_entrenadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(48, 48, 48)
                        .addComponent(btn_Entrenador))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("No sancionados"));

        jScrollPane1.setViewportView(lst_noSancionado);

        btn_ObtenerEquipos.setText("Obtener Equipos");
        btn_ObtenerEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ObtenerEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ObtenerEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(btn_ObtenerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_OrdenarPuntos.setText("Ordenar Por Puntos");
        btn_OrdenarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrdenarPuntosActionPerformed(evt);
            }
        });

        btn_guardarTodo.setText("Guardar Todo .txt");
        btn_guardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarTodoActionPerformed(evt);
            }
        });

        btn_OrdenarTodo.setText("Recuperar   txt");
        btn_OrdenarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrdenarTodoActionPerformed(evt);
            }
        });

        btn_guardarXml.setText("Guardar Todo xml");
        btn_guardarXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarXmlActionPerformed(evt);
            }
        });

        btn_guardarJson.setText("Guardar Todo json");
        btn_guardarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarJsonActionPerformed(evt);
            }
        });

        btn_recuperarXml.setText("Recuperar xml");
        btn_recuperarXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarXmlActionPerformed(evt);
            }
        });

        btn_recuperarJson.setText("Recuperar Json");
        btn_recuperarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarJsonActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar Seriando");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_recuperarSeriando.setText("Recuperar Seriando");
        btn_recuperarSeriando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarSeriandoActionPerformed(evt);
            }
        });

        jButton3.setText("Ordenar por Entrenador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ordenar por Equipo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Abrir nueva ventana ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sancionados"));
        jPanel4.setPreferredSize(new java.awt.Dimension(69, 305));

        lst_Sancionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lst_Sancionados);

        jButton6.setText("Obtener Equipos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_OrdenarPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guardarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarJson, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_OrdenarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_recuperarXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_recuperarJson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_recuperarSeriando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_OrdenarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_guardarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_OrdenarTodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_recuperarXml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_recuperarJson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_guardarJson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(btn_recuperarSeriando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AltaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AltaEquipoActionPerformed
        // TODO add your handling code here:
        añadirEquipo();
        
        
    }//GEN-LAST:event_btn_AltaEquipoActionPerformed

    private void btn_EntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrenadorActionPerformed
    
    
        añadirEntrenador();

        
    }//GEN-LAST:event_btn_EntrenadorActionPerformed

    private void lst_EquiposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_EquiposValueChanged
        // TODO add your handling code here:

        
        seleccionarEquipo();
        
        
    }//GEN-LAST:event_lst_EquiposValueChanged

    private void lst_EntrenadoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_EntrenadoresValueChanged
        // TODO add your handling code here:
    seleccionarEntrenador();
        
    }//GEN-LAST:event_lst_EntrenadoresValueChanged

    
   
    private void btn_guardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarTodoActionPerformed
        guardarTexto();
    }//GEN-LAST:event_btn_guardarTodoActionPerformed

    private void btn_OrdenarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrdenarTodoActionPerformed
        // TODO add your handling code here:
       recuperarTodo();
    }//GEN-LAST:event_btn_OrdenarTodoActionPerformed

    private void btn_ObtenerEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ObtenerEquiposActionPerformed
    noSancionados();
    }//GEN-LAST:event_btn_ObtenerEquiposActionPerformed

    private void btn_OrdenarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrdenarPuntosActionPerformed
        // TODO add your handling code here:
        ordenarPuntos();
    }//GEN-LAST:event_btn_OrdenarPuntosActionPerformed

    private void btn_guardarXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarXmlActionPerformed
   
        guardarXML();
   
        
    
        
    }//GEN-LAST:event_btn_guardarXmlActionPerformed

    private void btn_recuperarXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarXmlActionPerformed
        // TODO add your handling code here:
             cargarXml();
    }//GEN-LAST:event_btn_recuperarXmlActionPerformed

    private void btn_guardarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarJsonActionPerformed
        // TODO add your handling code here:
        guardarJsonEquipos();
        guardarJsonEntrenadores();
        
    }//GEN-LAST:event_btn_guardarJsonActionPerformed

    private void btn_recuperarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarJsonActionPerformed
        cargarJsonEquipos();
        cargarJsonEntrenadores();
        
    }//GEN-LAST:event_btn_recuperarJsonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        abrirVentana();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        guardarSeriandoEntrenadores();
        guardarSeriandoEquipos();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_recuperarSeriandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarSeriandoActionPerformed

            cargarSeriandoEquipos();
            cargarSeriandoEntrenadores();
   
    }//GEN-LAST:event_btn_recuperarSeriandoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ordenarPorNombreEntrenador();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        ordenarPorNombreEquipo();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Sancionados();
    }//GEN-LAST:event_jButton6ActionPerformed

    /*Abrir Ventana*/
    public void abrirVentana(){
        ventanaNuevo nuevaVentana = new ventanaNuevo(this, true);
        nuevaVentana.setVisible(true);
    }
    
    /*texto*/
    public void guardarTexto(){
            FileWriter fw = null;
            PrintWriter pw = null;
            File fichero= null;
            equipo eq;
            Entrenador ent;
        try {
            fichero = new File("EquiposEntrenadores.txt");
            fw = new FileWriter(fichero);
            pw = new PrintWriter(fw);
      
            
            
            for(int i =0; i<listaEquipos.getSize();i++){
                eq = (equipo) listaEquipos.get(i);
                pw.println("Equipo:"+ eq.getNombre()+":" +eq.getEntrenador()+":"+ eq.getPuntos() );
            }
            
           for(int i =0; i<listaEntrenadores.getSize();i++){
                ent = (Entrenador) listaEntrenadores.get(i);
                pw.println("Entrenador:"+ ent.getNombre()+":" + ent.getEdad());
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            pw.close();
        }
        
    }
    
    public void recuperarTodo(){
            listaEntrenadores.clear();
            listaEquipos.clear();
            FileReader fr = null;
            BufferedReader br = null;
            File fichero=null;

           
            String []trozos;
            
            String linea="",nombre,entrenador,nombreEntrenador;
            double puntos;
            
            int edad;
            
            
            equipo equi;
            Entrenador entr;
           
        try {
           
            fichero = new File("EquiposEntrenadores.txt");
            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
            
            
            while((linea=br.readLine())!=null){
              trozos = linea.split(":");
              
                if(trozos[0].equalsIgnoreCase("equipo")){
                        
                        nombre = trozos[1];
                        entrenador = trozos[2];
                        puntos = Double.parseDouble(trozos[3]);
                        equi = new equipo(nombre,puntos, entrenador);
                        listaEquipos.addElement(equi); 
            }else if(trozos[0].equalsIgnoreCase("entrenador")){
                       
                        nombreEntrenador = trozos[1];
                        edad = Integer.parseInt(trozos[2]);
                        entr = new Entrenador(nombreEntrenador, edad);
                        listaEntrenadores.addElement(entr);
            }
                
               
            }
            
         
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    



    /*añadir*/
    public void añadirEquipo(){
        equipo eq;
        
        eq = new equipo(txf_equipoNombre.getText(),Double.parseDouble(txf_equipoPuntos.getText()),txf_equiposEntrenador.getText());
        
        listaEquipos.addElement(eq);
        
        txf_equipoNombre.setText("");
        txf_equipoPuntos.setText("");
        txf_equiposEntrenador.setText("");
    }
    
    public void añadirEntrenador(){
        Entrenador ent;
        
        ent = new Entrenador(txt_entrenadorNombre.getText(), Integer.parseInt(txt_entrenadorEdad.getText()));
        
        listaEntrenadores.addElement(ent);
        
               
        txt_entrenadorEdad.setText("");
        txt_entrenadorNombre.setText("");
    }
    
    
    /*seleccionar*/
    public void seleccionarEquipo(){
        equipo eq;
        
        eq = (equipo) listaEquipos.get(lst_Equipos.getSelectedIndex());
        
        txf_equipoNombre.setText(eq.getNombre());
        txf_equipoPuntos.setText(""+eq.getPuntos());
        txf_equiposEntrenador.setText(eq.getEntrenador());
    }
    
    public void seleccionarEntrenador(){
        Entrenador ent;
        
        ent = (Entrenador) listaEntrenadores.get(lst_Entrenadores.getSelectedIndex());
        
        txt_entrenadorNombre.setText(ent.getNombre());
        txt_entrenadorEdad.setText(""+ent.getEdad());
    }

    
    /*ordenar*/
    public void ordenarPuntos(){
        equipo[] w = new equipo[listaEquipos.size()];
        listaEquipos.copyInto(w);
        listaEquipos.clear();
        Arrays.sort(w, new compararPuntos());
        
        for(int i=0; i<w.length;i++)
        {
            listaEquipos.addElement(w[i]);
        }
        
        lst_Equipos.updateUI();
    }
   
    public void ordenarPorNombreEntrenador(){
        Entrenador[] w = new Entrenador[listaEntrenadores.size()];
        listaEntrenadores.copyInto(w);
        listaEntrenadores.clear();
        Arrays.sort(w);
        
        for(int i=0; i<w.length;i++)
        {
            listaEntrenadores.addElement(w[i]);
        }
        
        lst_Entrenadores.updateUI();
    }
    
    public void ordenarPorNombreEquipo(){
        equipo[] w = new equipo[listaEquipos.size()];
        listaEquipos.copyInto(w);
        listaEquipos.clear();
        Arrays.sort(w);
        
        for(int i=0; i<w.length;i++)
        {
            listaEquipos.addElement(w[i]);
        }
        
        lst_Equipos.updateUI();
    }

    
    /*xml*/
    public void guardarXML(){
     
        
        try {
            DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
            
            doc = docBuilder.newDocument();
            Element rootElement = doc.createElement("Futbol");
            Element rootEquipo = doc.createElement("Equipos");
            Element rootEntrenadores = doc.createElement("Entrenadores");

            doc.appendChild(rootElement);
            rootElement.appendChild(rootEquipo);
            rootElement.appendChild(rootEntrenadores);
            
            for(int i=0;i<listaEquipos.getSize();i++){
                
                Element equipo1 = doc.createElement("Equipo");
                
                equipo e = (equipo) listaEquipos.get(i);
                
                Element nombre = doc.createElement("nombreEq");
                nombre.setTextContent(e.getNombre());
                equipo1.appendChild(nombre);
                
                Element puntos = doc.createElement("puntos");
                puntos.setTextContent(""+e.getPuntos());
                equipo1.appendChild(puntos);
                
                Element entrenador = doc.createElement("nombreEntrenador");
                entrenador.setTextContent(e.getEntrenador());
                equipo1.appendChild(entrenador);
                
                
                rootEquipo.appendChild(equipo1);       
            }
            
            
                for(int i=0;i<listaEntrenadores.getSize();i++){
                
                Element entrenador1 = doc.createElement("Entrenador");
                
                Entrenador e = (Entrenador) listaEntrenadores.get(i);
                
                Element nombre = doc.createElement("nombreEn");
                nombre.setTextContent(e.getNombre());
                entrenador1.appendChild(nombre);
                
                Element edad = doc.createElement("edad");
                edad.setTextContent(""+e.getEdad());
                entrenador1.appendChild(edad);
                
            
                
                
                rootEntrenadores.appendChild(entrenador1);       
            }
            
            
            
            
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);
         
            StreamResult result = new StreamResult(new File("equipos.xml"));             
            transformer.transform(source, result);
              
            
            
            
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public Entrenador obtenerEntrenador(Element l){
        
        String nombre;
        int edad;
        
        Element el=null;
        NodeList lista = null;
        
        Entrenador ent;
        
        lista = l.getElementsByTagName("nombreEn");
        el = (Element) lista.item(0);
        nombre = el.getTextContent();
        
        lista = l.getElementsByTagName("edad");
        el = (Element) lista.item(0);
        edad = Integer.parseInt(el.getTextContent());
        
        
        ent = new Entrenador(nombre, edad);
        
        return ent;

    }
    
    public equipo obtenerEquipo(Element l){
        
        String nombreEquipo, nombreEntrenador;
        double puntos;
        
        Element el= null;
        NodeList lista = null;
        
        equipo eq;
        
        lista = l.getElementsByTagName("nombreEq");
        el = (Element) lista.item(0);
        nombreEquipo = el.getTextContent();
         
        lista = l.getElementsByTagName("puntos");
        el = (Element) lista.item(0);
        puntos = Double.parseDouble(el.getTextContent());
        
        lista = l.getElementsByTagName("nombreEntrenador");
        el = (Element) lista.item(0);
        nombreEntrenador = el.getTextContent();
        
        eq = new equipo(nombreEquipo, puntos, nombreEntrenador);
      
        return eq;
        
    }
    
    public void cargarXml(){
        listaEquipos.clear();
        listaEntrenadores.clear();
        
        try {
            
            
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            
            DocumentBuilder db = dbf.newDocumentBuilder();
            
            Document doc = db.parse("equipos.xml");
            
            raiz = doc.getDocumentElement();
            
            NodeList nlEquipos = doc.getElementsByTagName("Equipo");
            
            Element elementoEquipo;
            
            for(int i=0;i<nlEquipos.getLength();i++){
                equipo e = null;
                elementoEquipo = (Element) nlEquipos.item(i);
                
                e = obtenerEquipo(elementoEquipo);

                listaEquipos.addElement(e);
            }
            
            
            NodeList nlEntrenadores= doc.getElementsByTagName("Entrenador");
            Element elementoEntrenador;
            
            for(int i =0; i<nlEntrenadores.getLength();i++){
                Entrenador e = null;
                elementoEntrenador = (Element) nlEntrenadores.item(i);
                e = obtenerEntrenador(elementoEntrenador);
                listaEntrenadores.addElement(e);
            }
            
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              
        
        
    }
    
    
    
    
    
    /*json*/
    
    /*Guardar*/
    public void guardarJsonEquipos(){

            FileWriter fw = null;
            PrintWriter pw = null;
            File fEquipos = new File("equipos.json");
   
            
          
            ArrayList almacenEquipos = new ArrayList<equipo>();
          
            

            for(int i = 0;i<listaEquipos.getSize();i++){
                equipo e = (equipo) listaEquipos.get(i);
             
                almacenEquipos.add(e);
            }
       
            
  
            
            Gson gson = new Gson();
            String rJsonEquipo = gson.toJson(almacenEquipos);
   
            
            
        try {
            fw = new FileWriter(fEquipos);
            pw = new PrintWriter(fw);
            pw.println(rJsonEquipo);
      
           
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            pw.close();
        }
        
        
    }
    
    public void guardarJsonEntrenadores(){
        
            FileWriter fw = null;
            PrintWriter pw = null;
            
            File fEntrenadores=new File("entrenadores.json");
        
            ArrayList almacenEntrenadores = new ArrayList<Entrenador>();
        
            for(int i = 0;i<listaEntrenadores.getSize();i++){
                Entrenador ent = (Entrenador) listaEntrenadores.get(i);
                almacenEntrenadores.add(ent);
            }
       
            
          
            Gson gson = new Gson();
            String rJsonEntrenadores = gson.toJson(almacenEntrenadores);
            
            
        try {
   
      
            
            fw = new FileWriter(fEntrenadores);
             pw = new PrintWriter(fw);
             pw.println(rJsonEntrenadores);
            
            
           
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            pw.close();
        }
    }

    /*Cargar Json*/
    public void cargarJsonEquipos(){

        
            listaEquipos.clear();
            
            equipo eq = null;
         
            Gson cargarGson = new Gson();
            BufferedReader br = null;
            
            ArrayList almacenEquipos = new ArrayList<equipo>();
            
           
        try {
            
            br = new BufferedReader(new FileReader("equipos.json"));
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         java.lang.reflect.Type tipoListaEquipos = new TypeToken<List<equipo>>(){}.getType(); 
         List<equipo> lequipos = cargarGson.fromJson(br, tipoListaEquipos);
          for (int i =0; i<lequipos.size();i++)
        {
            eq = (equipo)lequipos.get(i);
            listaEquipos.addElement(eq);

             }
        }

    public void cargarJsonEntrenadores(){
            
               listaEntrenadores.clear();
        
               Entrenador ent = null;
               Gson cargarGson = new Gson();
               
               BufferedReader br=null;
               ArrayList almacenEntrenadores= new ArrayList<Entrenador>();
               
               try{
                   
                   br = new BufferedReader(new FileReader("entrenadores.json"));
                   
               }catch(FileNotFoundException ex){
                   
               }
               java.lang.reflect.Type tipoListaEntrenadores = new TypeToken<List<Entrenador>>(){}.getType();
               List<Entrenador> lEntrenadores = cargarGson.fromJson(br, tipoListaEntrenadores);
               
               for(int i=0; i<lEntrenadores.size();i++){
                   
                   ent = (Entrenador) lEntrenadores.get(i);
                   listaEntrenadores.addElement(ent);
                   
               }
               
    }
    
    
    /*seriando*/
    
    public void guardarSeriandoEquipos(){
        
        equipo eq;

        FileOutputStream fos;
        ObjectOutputStream oos;
        
        
        try{
            
            fos = new FileOutputStream("Equipos.dat");
            oos = new ObjectOutputStream(fos);
            
            for(int i=0;i<listaEquipos.getSize();i++){
                
                eq = (equipo)listaEquipos.get(i);
                oos.writeObject(eq);
                
            }
        
  
        }catch(java.lang.NumberFormatException ex){
            
        }catch(IOException ex){
            
        }
        
        
        
    }
    
    public void guardarSeriandoEntrenadores(){
         
        Entrenador ent;
        
        FileOutputStream fos;
        ObjectOutputStream oos;
        
        
        try{
            
            fos = new FileOutputStream("Entrenadores.dat");
            oos = new ObjectOutputStream(fos);
            
      
            for(int j=0;j<listaEntrenadores.getSize();j++){
                
                ent = (Entrenador)listaEntrenadores.get(j);
                oos.writeObject(ent);
                
            }
            
            
        }catch(java.lang.NumberFormatException ex){
            
        }catch(IOException ex){
            
        }
        
            
        }
    
    public void cargarSeriandoEquipos() {
        
        try {
            listaEquipos.clear();
            

            FileInputStream fis;
            ObjectInputStream ois;
            equipo eq = null;
            
            
            fis = new FileInputStream("Equipos.dat");
            ois = new ObjectInputStream(fis);
            
            
            while((eq = (equipo) ois.readObject())!=null){
                
                listaEquipos.addElement(eq);
            }
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
            
        } catch (ClassNotFoundException ex) {
          
        }

     
        
        
    }
    
    public void cargarSeriandoEntrenadores(){
            listaEntrenadores.clear();
            
            FileInputStream fis;
            ObjectInputStream ois;
            Entrenador ent = null;
        try {
       
            
            fis = new FileInputStream("Entrenadores.dat");
            ois = new ObjectInputStream(fis);
            
            
            while((ent = (Entrenador) ois.readObject())!=null){
               listaEntrenadores.addElement(ent);
            }
                
                
            
            
            
    }   catch (FileNotFoundException ex) {
        
        } catch (IOException ex) {
           
        } catch (ClassNotFoundException ex) {
            
        }
    }
    
   
    /*Sancionadors*/
    public void Sancionados(){
            
            listaSancionados.clear();
        
            FileReader fr = null;
            BufferedReader br = null;
            File fichero=null;

           
            String []trozos;
            
            String linea="";
    
        
            Entrenador entr;
           
        try {
           
            fichero = new File("sancionados.txt");
            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
            
            
            while((linea=br.readLine())!=null){
              trozos = linea.split(";");
              
              for(int i=0; i<trozos.length;i++){
                  for(int j =0; j<listaEntrenadores.getSize();j++){
                      Entrenador ent = (Entrenador) listaEntrenadores.get(j);
                   if(trozos[i].equalsIgnoreCase(ent.toString())){
                       listaSancionados.addElement(ent);
                   }
                  }
                 
              }
                
               
            }
            
         
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void noSancionados(){
            listaSancionados.clear();
        
            FileReader fr = null;
            BufferedReader br = null;
            File fichero=null;
            ArrayList almacenEntrenadores= new ArrayList<Entrenador>();
            ArrayList noSancionados = new ArrayList<>();
            String []trozos=null;
            
            String linea="";
    
        
            Entrenador entr;
            
            boolean condition=true;
     
        try {
           
            fichero = new File("sancionados.txt");
            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
            
            
            while((linea=br.readLine())!=null){
              trozos = linea.split(";");
                 
            }
     
       
       
           
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(guiEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /*sancionados*/
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AltaEquipo;
    private javax.swing.JButton btn_Entrenador;
    private javax.swing.JButton btn_ObtenerEquipos;
    private javax.swing.JButton btn_OrdenarPuntos;
    private javax.swing.JButton btn_OrdenarTodo;
    private javax.swing.JButton btn_guardarJson;
    private javax.swing.JButton btn_guardarTodo;
    private javax.swing.JButton btn_guardarXml;
    private javax.swing.JButton btn_recuperarJson;
    private javax.swing.JButton btn_recuperarSeriando;
    private javax.swing.JButton btn_recuperarXml;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lst_Entrenadores;
    private javax.swing.JList<String> lst_Equipos;
    private javax.swing.JList<String> lst_Sancionados;
    private javax.swing.JList<String> lst_noSancionado;
    private javax.swing.JTextField txf_equipoNombre;
    private javax.swing.JTextField txf_equipoPuntos;
    private javax.swing.JTextField txf_equiposEntrenador;
    private javax.swing.JTextField txt_entrenadorEdad;
    private javax.swing.JTextField txt_entrenadorNombre;
    // End of variables declaration//GEN-END:variables
}
