/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad.pkg5.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    primerFrame pr1 = new primerFrame();
    segundoFrame sf1 = new segundoFrame();
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mItem_Calculadora = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mItem_IMC = new javax.swing.JMenuItem();
        mBar_help = new javax.swing.JMenu();
        mItem_Version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mItem_Calculadora.setText("Programas");

        jMenuItem1.setText("Calculadora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mItem_Calculadora.add(jMenuItem1);

        mItem_IMC.setText("IMC");
        mItem_IMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_IMCActionPerformed(evt);
            }
        });
        mItem_Calculadora.add(mItem_IMC);

        jMenuBar1.add(mItem_Calculadora);

        mBar_help.setText("Ayuda");

        mItem_Version.setText("Versión");
        mItem_Version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_VersionActionPerformed(evt);
            }
        });
        mBar_help.add(mItem_Version);

        jMenuBar1.add(mBar_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           // TODO add your handling code here:
          
        
        if(pr1.isVisible()){
        
        }else{
            pr1.setVisible(true);
        }
        

     

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mItem_VersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_VersionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane ,"Versión: 1.0.0 .\n"
                                               +"Francisco Carlos Zaragoza Beato");
        
     
    }//GEN-LAST:event_mItem_VersionActionPerformed

    private void mItem_IMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_IMCActionPerformed
        // TODO add your handling code here:
        if(sf1.isVisible()){
              
        }else{
            sf1.setVisible(true);
        }
        
        
    }//GEN-LAST:event_mItem_IMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mBar_help;
    private javax.swing.JMenu mItem_Calculadora;
    private javax.swing.JMenuItem mItem_IMC;
    private javax.swing.JMenuItem mItem_Version;
    // End of variables declaration//GEN-END:variables
}
