/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad.pkg5.pkg7.buena;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author david
 */
public class equiposGUI extends javax.swing.JFrame {

    
    private String nombreEquipo, nombreEntrenador, nombre;
    private int puntos,edad;
    
    Document doc = null;
    Element raiz = null;
    
    Gson gson = new Gson();
    
    private DefaultListModel dlmEquipos = new DefaultListModel();
    private DefaultListModel dlmEntrenadores = new DefaultListModel();
    private DefaultListModel dlmSancionados = new DefaultListModel();
    private int contador = 0;
    /**
     * Creates new form equiposGUI
     */
    public equiposGUI() {
        initComponents();
        lst_equipos.setModel(dlmEquipos);
        lst_entrenadores.setModel(dlmEntrenadores);
        lst_sancionados.setModel(dlmSancionados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txf_nombreEquipo = new javax.swing.JTextField();
        txf_nombreEntrenador = new javax.swing.JTextField();
        txf_puntos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_equipos = new javax.swing.JList<>();
        btn_añadirEquipo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_edad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_entrenadores = new javax.swing.JList<>();
        btn_añadirEntrenador = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_sancionados = new javax.swing.JList<>();
        btn_equiposNoSancionados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itm_guardarTXT = new javax.swing.JMenuItem();
        itm_recuperarTXT = new javax.swing.JMenuItem();
        itm_guardarXML = new javax.swing.JMenuItem();
        itm_recuperarXML = new javax.swing.JMenuItem();
        itm_guardarJSON = new javax.swing.JMenuItem();
        itm_recuperarJSON = new javax.swing.JMenuItem();
        itm_guardarSeriando = new javax.swing.JMenuItem();
        itm_recuperarSeriando = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EQUIPOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entrenador");

        lst_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDatosEquipo(evt);
            }
        });
        jScrollPane1.setViewportView(lst_equipos);

        btn_añadirEquipo.setText("ALTA");
        btn_añadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txf_nombreEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(txf_nombreEntrenador)
                                .addComponent(txf_puntos)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(btn_añadirEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txf_nombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txf_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(btn_añadirEquipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTRENADORES");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edad");

        lst_entrenadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDatosEntrenador(evt);
            }
        });
        jScrollPane2.setViewportView(lst_entrenadores);

        btn_añadirEntrenador.setText("ALTA");
        btn_añadirEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirEntrenadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_añadirEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_añadirEntrenador)
                        .addGap(49, 49, 49))))
        );

        jButton1.setText("ORDENAR POR PUNTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Equipos con entrenadores no sancionados");

        jScrollPane3.setViewportView(lst_sancionados);

        btn_equiposNoSancionados.setText("OBTENER EQUIPOS");
        btn_equiposNoSancionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equiposNoSancionadosActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        itm_guardarTXT.setText("Guardar en fichero texto");
        itm_guardarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_guardarTXTActionPerformed(evt);
            }
        });
        jMenu1.add(itm_guardarTXT);

        itm_recuperarTXT.setText("Recuperar de fichero texto");
        itm_recuperarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_recuperarTXTActionPerformed(evt);
            }
        });
        jMenu1.add(itm_recuperarTXT);

        itm_guardarXML.setText("Guardar en XML");
        itm_guardarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_guardarXMLActionPerformed(evt);
            }
        });
        jMenu1.add(itm_guardarXML);

        itm_recuperarXML.setText("Recuperar de XML");
        itm_recuperarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_recuperarXMLActionPerformed(evt);
            }
        });
        jMenu1.add(itm_recuperarXML);

        itm_guardarJSON.setText("Guardar en JSON");
        itm_guardarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_guardarJSONActionPerformed(evt);
            }
        });
        jMenu1.add(itm_guardarJSON);

        itm_recuperarJSON.setText("Recuperar de JSON");
        itm_recuperarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_recuperarJSONActionPerformed(evt);
            }
        });
        jMenu1.add(itm_recuperarJSON);

        itm_guardarSeriando.setText("Guardar en Seriando");
        jMenu1.add(itm_guardarSeriando);

        itm_recuperarSeriando.setText("Recuperar de Seriando");
        jMenu1.add(itm_recuperarSeriando);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(btn_equiposNoSancionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_equiposNoSancionados)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDatosEquipo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosEquipo
        Equipo e = (Equipo) dlmEquipos.getElementAt(lst_equipos.getSelectedIndex());
        
        txf_nombreEquipo.setText(e.getNombreEquipo());
        txf_nombreEntrenador.setText(e.getNombreEntrenador());
        txf_puntos.setText(""+e.getPuntos());
    }//GEN-LAST:event_mostrarDatosEquipo

    private void mostrarDatosEntrenador(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosEntrenador
        Entrenador e = (Entrenador) dlmEntrenadores.getElementAt(lst_entrenadores.getSelectedIndex());
        
        txf_nombre.setText(e.getNombre());
        txf_edad.setText(""+e.getEdad());
    }//GEN-LAST:event_mostrarDatosEntrenador

    private void btn_añadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirEquipoActionPerformed
        nombreEquipo = txf_nombreEquipo.getText();
        puntos = Integer.parseInt(txf_puntos.getText());
        nombreEntrenador = txf_nombreEntrenador.getText();
        
        Equipo e = new Equipo(nombreEquipo, nombreEntrenador, puntos);
        dlmEquipos.addElement(e);
        
        txf_nombreEquipo.setText(null);
        txf_nombreEntrenador.setText(null);
        txf_nombreEntrenador.setText(null);
        
        contador++;
    }//GEN-LAST:event_btn_añadirEquipoActionPerformed

    private void btn_añadirEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirEntrenadorActionPerformed
        nombre = txf_nombre.getText();
        edad = Integer.parseInt(txf_edad.getText());
        
        Entrenador e = new Entrenador(nombre, edad);
        dlmEntrenadores.addElement(e);
        
        txf_nombre.setText(null);
        txf_edad.setText(null);
        
        contador++;
    }//GEN-LAST:event_btn_añadirEntrenadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Equipo[] arrayEquipos = new Equipo[dlmEquipos.size()];
        dlmEquipos.copyInto(arrayEquipos);
        dlmEquipos.clear();
        Arrays.sort(arrayEquipos, new OrdenarPorPuntos());
        
        for(int i=0; i<arrayEquipos.length;i++)
        {
            dlmEquipos.addElement(arrayEquipos[i]);
        }
        
        lst_equipos.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itm_guardarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_guardarTXTActionPerformed
        FileWriter fw=null;
        PrintWriter pw=null;
        
        JFileChooser fileChooser =  new JFileChooser("./");
        int seleccion = fileChooser.showSaveDialog(this);
        File f;
        
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            f = fileChooser.getSelectedFile();
        
            try
            {
                fw = new FileWriter(f);
                pw = new PrintWriter(fw);

                for(int i=0;i<dlmEquipos.getSize();i++)
                {
                    Equipo e = (Equipo) dlmEquipos.get(i);
                    pw.println("Equipo"+";"+e.getNombreEquipo()+";"+e.getNombreEntrenador()+";"+e.getPuntos());
                }
                
                for (int j = 0; j < dlmEntrenadores.getSize(); j++) 
                {
                    Entrenador e = (Entrenador) dlmEntrenadores.get(j);
                    pw.println("Entrenador"+";"+e.getNombre()+";"+e.getEdad());
                }
                    
            }
            catch(IOException ex)
            {
                Logger.getLogger(equiposGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            finally
            {
                try
                {
                    fw.close();
                }
                catch(Exception e2)
                {
                    e2.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_itm_guardarTXTActionPerformed

    private void btn_equiposNoSancionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equiposNoSancionadosActionPerformed
        
        ArrayList Sancionados = new ArrayList();
        FileReader fr = null;
        BufferedReader br = null;

        try {

            fr = new FileReader("Sancionados.txt");
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {

                String[] Almacen = (linea.split(";"));

                for (int i = 0; i < Almacen.length; i++) {
                    Sancionados.add(Almacen[i]);
                }

            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {

            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

        Equipo e1;

        dlmSancionados.removeAllElements();

        for (int i = 0; i < dlmEquipos.size(); i++) {

            e1 = (Equipo) dlmEquipos.getElementAt(i);

            for (int j = 0; j < Sancionados.size(); j++) {

                String nom = (String) Sancionados.get(j);

                if (e1.compareTo(Sancionados.get(j)) == 0) {

                    if ((e1.getNombreEntrenador().equalsIgnoreCase(nom))) {
                        dlmSancionados.addElement(e1);
                    }
                }
            }
        }

        lst_sancionados.updateUI();
    }//GEN-LAST:event_btn_equiposNoSancionadosActionPerformed

    private void itm_recuperarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_recuperarTXTActionPerformed
        
        FileReader fr=null;
        BufferedReader br=null;
        String linea =null;
        String trozos[];
        dlmEquipos.clear();
        dlmEntrenadores.clear();
       
        try
        {
            fr = new FileReader("EquiposEntrenadores.txt");
            br = new BufferedReader(fr);


            while((linea = br.readLine())!=null)
            {
                trozos = linea.split(";");

                if (trozos[0].equals("Equipo"))
                {
                    Equipo e = new Equipo(trozos[1].trim(),trozos[2].trim(),Integer.parseInt(trozos[3].trim()));
                    dlmEquipos.addElement(e);  
                    lst_equipos.setModel(dlmEquipos);
                    lst_equipos.updateUI();
                }
                else
                {
                    Entrenador en = new Entrenador(trozos[1],Integer.parseInt(trozos[2].trim()));
                    dlmEntrenadores.addElement(en);
                    lst_entrenadores.setModel(dlmEntrenadores);
                    lst_entrenadores.updateUI();                        
                }                                                            
            }
        }
        catch(FileNotFoundException ex)
        {
            System.out.println(ex.getMessage());
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
        finally
        {
            try
            {
                fr.close();
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
      
    }//GEN-LAST:event_itm_recuperarTXTActionPerformed

    private void itm_guardarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_guardarXMLActionPerformed
        try
        {
            DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
            
            doc = docBuilder.newDocument();
            Element rootElement = doc.createElement("Liga");
            Element rootEquipos = doc.createElement("Equipos");
            Element rootEntrenadores = doc.createElement("Entrenadores");
            doc.appendChild(rootElement);
            
            rootElement.appendChild(rootEquipos);
            rootElement.appendChild(rootEntrenadores);
            
            for (int i = 0; i < dlmEquipos.getSize(); i++) 
            {
                
                Element equipo = doc.createElement("Equipo");
                Equipo e = (Equipo) dlmEquipos.get(i);
                
                Element e1 = doc.createElement("NombreEquipo");
                e1.setTextContent(e.getNombreEquipo());
                equipo.appendChild(e1);

                Element e2 = doc.createElement("NombreEntrenador");
                e2.setTextContent(e.getNombreEntrenador());
                equipo.appendChild(e2);
                
                Element e3 = doc.createElement("Puntos");
                e3.setTextContent(""+e.getPuntos());
                equipo.appendChild(e3);
                
                rootEquipos.appendChild(equipo);
                         
            }
            
            for (int i = 0; i < dlmEntrenadores.getSize(); i++) 
            {
                Element entrenador = doc.createElement("Entrenador");
                Entrenador e = (Entrenador) dlmEntrenadores.get(i);
                rootEntrenadores.appendChild(entrenador);
                
                Element e1 = doc.createElement("Nombre");
                e1.setTextContent(e.getNombre());
                entrenador.appendChild(e1);
                
                Element e2 = doc.createElement("Edad");
                e2.setTextContent(""+e.getEdad());
                entrenador.appendChild(e2);
                
                rootEntrenadores.appendChild(entrenador);
            }
            
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);   

            StreamResult result = new StreamResult(new File("equipos.xml"));
            transformer.transform(source, result);       
        }
        catch (ParserConfigurationException pce)
        {
            pce.printStackTrace();
        }
        catch (TransformerException tfe)
        {
            tfe.printStackTrace();
        }
    }//GEN-LAST:event_itm_guardarXMLActionPerformed

    private void itm_recuperarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_recuperarXMLActionPerformed
        
        dlmEquipos.removeAllElements();
        dlmEntrenadores.removeAllElements();
        try 
        {            
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            
            doc = db.parse("equipos.xml");
            raiz = doc.getDocumentElement();

            NodeList nl = doc.getElementsByTagName("Equipo");
            Element equ = null;

            NodeList n2 = doc.getElementsByTagName("Entrenador");
            Element ent = null;

            for (int i = 0; i < nl.getLength(); i++) {

                Equipo l = null;
                equ = (Element) nl.item(i);
                l = obtenerEquipo(equ);
                dlmEquipos.addElement(l);
            }

            for (int i = 0; i < n2.getLength(); i++) {

                Entrenador e = null;
                ent = (Element) n2.item(i);
                e = obtenerEntrenador(ent);
                dlmEntrenadores.addElement(e);
            }

        } catch (Exception ex) {
            System.out.println("¡Error! No se ha podido cargar el documento XML.");
        }
    }//GEN-LAST:event_itm_recuperarXMLActionPerformed

    private void itm_guardarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_guardarJSONActionPerformed
        
        FileWriter fw = null;
        PrintWriter pw = null;

        ArrayList almacenEquipos = new ArrayList<Equipo>();

        ArrayList almacenEntrenadores = new ArrayList<Entrenador>();

        for (int i = 0; i < dlmEquipos.size(); i++) {
            Equipo e = (Equipo) dlmEquipos.get(i);
            almacenEquipos.add(e);
        }
        for (int j = 0; j < dlmEntrenadores.size(); j++) {
            Entrenador e = (Entrenador) dlmEntrenadores.get(j);
            almacenEntrenadores.add(e);
        }


        
        String rJson = gson.toJson(almacenEquipos);
        String rJson2 = gson.toJson(almacenEntrenadores);

        
        try 
        {
            pw = new PrintWriter(new FileWriter("equiposJSON.txt"));
            pw.print(rJson + " ");
            pw.append(rJson2);
        } 
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        } 
        finally 
        {
            pw.close();
        }
    }//GEN-LAST:event_itm_guardarJSONActionPerformed

    private void itm_recuperarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_recuperarJSONActionPerformed
        BufferedReader brs = null;
        dlmEquipos.clear();
        dlmEntrenadores.clear();

        String equipos = null, entrenadores = null, linea;
        try {

            brs = new BufferedReader(new FileReader("equiposJSON.txt"));

            while ((linea = brs.readLine()) != null) {

                String[] Almacen = (linea.split(" "));
                equipos = Almacen[0];
                entrenadores = Almacen[1];

            }
        } catch (Exception ex) {

            System.out.println(ex.getMessage());

        }

        java.lang.reflect.Type tipoListaEquipos = new TypeToken<List<Equipo>>() {
        }.getType();

        java.lang.reflect.Type tipoListaEntrenadores = new TypeToken<List<Entrenador>>() {
        }.getType();

        try {
            List<Equipo> lEquipo = gson.fromJson(equipos, tipoListaEquipos);

            for (Equipo eq : lEquipo) {
                dlmEquipos.addElement(eq);
            }

            List<Entrenador> lEntrenador = gson.fromJson(entrenadores, tipoListaEntrenadores);
            for (Entrenador en : lEntrenador) {
                dlmEntrenadores.addElement(en);
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_itm_recuperarJSONActionPerformed

    public Equipo obtenerEquipo(Element equ) 
    {
        Equipo e = null;
        String nombreEquipo, puntos, nombreEntrenador;
        int ipuntos;
        NodeList lista = null;
        Element el;
        
        lista = equ.getElementsByTagName("NombreEquipo");
        el = (Element) lista.item(0);
        nombreEquipo = el.getTextContent();

        
        lista = equ.getElementsByTagName("NombreEntrenador");
        el = (Element) lista.item(0);
        nombreEntrenador = el.getTextContent();
        

        lista = equ.getElementsByTagName("Puntos");
        el = (Element) lista.item(0);
        puntos = el.getTextContent();
        ipuntos = Integer.parseInt(puntos);
        

        e = new Equipo(nombreEquipo, nombreEntrenador, ipuntos);

        return e;
    }
    
    public Entrenador obtenerEntrenador(Element equ) {
        
        Entrenador e = null;
        String nombre, edad;
        int iedad;
        NodeList lista = null;
        Element el;
        //NOMBRE 
        lista = equ.getElementsByTagName("Nombre");
        el = (Element) lista.item(0);
        nombre = el.getTextContent();
        //edad
        lista = equ.getElementsByTagName("Edad");
        el = (Element) lista.item(0);
        edad = el.getTextContent();
        iedad = Integer.parseInt(edad);

        e = new Entrenador(nombre, iedad);

        return e;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equiposGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equiposGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equiposGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equiposGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equiposGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirEntrenador;
    private javax.swing.JButton btn_añadirEquipo;
    private javax.swing.JButton btn_equiposNoSancionados;
    private javax.swing.JMenuItem itm_guardarJSON;
    private javax.swing.JMenuItem itm_guardarSeriando;
    private javax.swing.JMenuItem itm_guardarTXT;
    private javax.swing.JMenuItem itm_guardarXML;
    private javax.swing.JMenuItem itm_recuperarJSON;
    private javax.swing.JMenuItem itm_recuperarSeriando;
    private javax.swing.JMenuItem itm_recuperarTXT;
    private javax.swing.JMenuItem itm_recuperarXML;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_entrenadores;
    private javax.swing.JList<String> lst_equipos;
    private javax.swing.JList<String> lst_sancionados;
    private javax.swing.JTextField txf_edad;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JTextField txf_nombreEntrenador;
    private javax.swing.JTextField txf_nombreEquipo;
    private javax.swing.JTextField txf_puntos;
    // End of variables declaration//GEN-END:variables
}
